export default {
  name: 'Underscore Finance',
  description: 'Underscore Finance',
  targetPath: './src/contracts',
  // eslint-disable-next-line no-undef
  etherscanApiKey: process.env.BASESCAN_API_KEY,
  etherscanApi: 'https://api.basescan.org',
  isModule: true,
  isSdk: true,
  contracts: {
    AddyRegistry: { address: '0xdCCaB9855D7eE558409EBdf358a3A44a8b2415B3' },
    AgentFactory: { address: '0x484637E77C66eaE88C8Edb64E09c5057F52866BE' },
    UserWallet: { isTemplate: true, address: '0xf614Bb656a8B1B8646b25f3Ca4a9655E407D38e5' },
    UserWalletConfig: { isTemplate: true, address: '0xAeE931cC57CfBE31328bCfF092Af7eC7dFD7EBC8' },
    Agent: { isTemplate: true, address: '0x2e3754aD00DcC1c31Ee1Ea46379DA83bD02896F7' },
    LegoRegistry: { address: '0x5dC5A7304a1f2feeadF491b8F62BD41687CB330b' },
    OracleRegistry: { address: '0x4D97d514d92Efd711D0645fE0759fA68480facc5' },
    PriceSheets: { address: '0x38Cd202B42b3906051573174e506b5b6BC83D47C' },
    LegoHelper: { address: '0xF2920Dcb5298D48755b49a5e91F073D47A25439b' },
    ChainlinkFeeds: { address: '0x5e06882026739D91541b4F979FbF40057C75aB96' },
    PythFeeds: { address: '0x56cC721FA002425b074e767A1F7B663Eb00C7535' },
    StorkFeeds: { address: '0x37Ce94Ec6A9072ee1231eff57A8987448aDb8E0a' },
    LegoAaveV3: { address: '0x580729527620ab496195465bfFD15E89eFb508B4' },
    LegoCompoundV3: { address: '0x71fC412B72e052F91AEF0e11084D7cEb99ae275c' },
    LegoEuler: { address: '0x29e0815b2c801D6946bD05EB0A5c9b5a510d88f1' },
    LegoFluid: { address: '0x76765fcd0A666fAc585e520C421FcD881ca0d861' },
    LegoMoonwell: { address: '0x959753dB45E61Cf7dCc6057279A57AC286830C28' },
    LegoMorpho: { address: '0xF7B09b7E6528037e125Ac8d3Ed047A39d10A32AF' },
    LegoSky: { address: '0x6c2496434a42779A1c5dc62C18B3177C1771Bb80' },
    LegoAeroClassic: { address: '0xF66d2FD9Ee2975DF518c6bA9D2ff7d562EE8530b' },
    LegoAeroSlipstream: { address: '0xe819d6367d393AD952265Ed34b2A9A67a3F1423A' },
    LegoCurve: { address: '0x3EadC664BE12D7Ef39ACf50C48695ff8614127f1' },
    LegoUniswapV2: { address: '0xC9Eeeab623B1cd6b53a03938Df5eBf9B7d3d2C0F' },
    LegoUniswapV3: { address: '0x5282BA17Ec8cF31c78404d0C57Fb7CfeabC212a0' },

    ERC20: {
      isTemplate: true,
      abi: [
        {
          type: 'event',
          name: 'Transfer',
          inputs: [
            {
              name: 'sender',
              type: 'address',
              indexed: true,
            },
            {
              name: 'receiver',
              type: 'address',
              indexed: true,
            },
            {
              name: 'amount',
              type: 'uint256',
              indexed: false,
            },
          ],
          anonymous: false,
        },
        {
          type: 'event',
          name: 'Approval',
          inputs: [
            {
              name: 'owner',
              type: 'address',
              indexed: true,
            },
            {
              name: 'spender',
              type: 'address',
              indexed: true,
            },
            {
              name: 'amount',
              type: 'uint256',
              indexed: false,
            },
          ],
          anonymous: false,
        },
        {
          type: 'function',
          name: 'name',
          stateMutability: 'pure',
          inputs: [],
          outputs: [
            {
              name: '',
              type: 'string',
            },
          ],
        },
        {
          type: 'function',
          name: 'symbol',
          stateMutability: 'pure',
          inputs: [],
          outputs: [
            {
              name: '',
              type: 'string',
            },
          ],
        },
        {
          type: 'function',
          name: 'decimals',
          stateMutability: 'pure',
          inputs: [],
          outputs: [
            {
              name: '',
              type: 'uint8',
            },
          ],
        },
        {
          type: 'function',
          name: 'transfer',
          stateMutability: 'nonpayable',
          inputs: [
            {
              name: '_recipient',
              type: 'address',
            },
            {
              name: '_amount',
              type: 'uint256',
            },
          ],
          outputs: [
            {
              name: '',
              type: 'bool',
            },
          ],
        },
        {
          type: 'function',
          name: 'transferFrom',
          stateMutability: 'nonpayable',
          inputs: [
            {
              name: '_sender',
              type: 'address',
            },
            {
              name: '_recipient',
              type: 'address',
            },
            {
              name: '_amount',
              type: 'uint256',
            },
          ],
          outputs: [
            {
              name: '',
              type: 'bool',
            },
          ],
        },
        {
          type: 'function',
          name: 'approve',
          stateMutability: 'nonpayable',
          inputs: [
            {
              name: '_spender',
              type: 'address',
            },
            {
              name: '_amount',
              type: 'uint256',
            },
          ],
          outputs: [
            {
              name: '',
              type: 'bool',
            },
          ],
        },
        {
          type: 'function',
          name: 'permit',
          stateMutability: 'nonpayable',
          inputs: [
            {
              name: '_owner',
              type: 'address',
            },
            {
              name: '_spender',
              type: 'address',
            },
            {
              name: '_amount',
              type: 'uint256',
            },
            {
              name: '_expiry',
              type: 'uint256',
            },
            {
              name: '_signature',
              type: 'bytes',
            },
          ],
          outputs: [
            {
              name: '',
              type: 'bool',
            },
          ],
        },
        {
          type: 'function',
          name: 'totalSupply',
          stateMutability: 'view',
          inputs: [],
          outputs: [
            {
              name: '',
              type: 'uint256',
            },
          ],
        },
        {
          type: 'function',
          name: 'balanceOf',
          stateMutability: 'view',
          inputs: [
            {
              name: 'arg0',
              type: 'address',
            },
          ],
          outputs: [
            {
              name: '',
              type: 'uint256',
            },
          ],
        },
        {
          type: 'function',
          name: 'allowance',
          stateMutability: 'view',
          inputs: [
            {
              name: 'arg0',
              type: 'address',
            },
            {
              name: 'arg1',
              type: 'address',
            },
          ],
          outputs: [
            {
              name: '',
              type: 'uint256',
            },
          ],
        },
        {
          type: 'function',
          name: 'nonces',
          stateMutability: 'view',
          inputs: [
            {
              name: 'arg0',
              type: 'address',
            },
          ],
          outputs: [
            {
              name: '',
              type: 'uint256',
            },
          ],
        },
        {
          type: 'function',
          name: 'DOMAIN_SEPARATOR',
          stateMutability: 'view',
          inputs: [],
          outputs: [
            {
              name: '',
              type: 'bytes32',
            },
          ],
        },
      ],
    },
    LegoCredit: {
      isTemplate: true,
      abi: [
        {
          stateMutability: 'nonpayable',
          type: 'function',
          name: 'borrow',
          inputs: [
            { name: '_borrowAsset', type: 'address' },
            { name: '_amount', type: 'uint256' },
            { name: '_recipient', type: 'address' },
          ],
          outputs: [
            { name: '', type: 'address' },
            { name: '', type: 'uint256' },
            { name: '', type: 'uint256' },
          ],
        },
        {
          stateMutability: 'nonpayable',
          type: 'function',
          name: 'borrow',
          inputs: [
            { name: '_borrowAsset', type: 'address' },
            { name: '_amount', type: 'uint256' },
            { name: '_recipient', type: 'address' },
            { name: '_oracleRegistry', type: 'address' },
          ],
          outputs: [
            { name: '', type: 'address' },
            { name: '', type: 'uint256' },
            { name: '', type: 'uint256' },
          ],
        },
        {
          stateMutability: 'nonpayable',
          type: 'function',
          name: 'repayDebt',
          inputs: [
            { name: '_paymentAsset', type: 'address' },
            { name: '_paymentAmount', type: 'uint256' },
            { name: '_recipient', type: 'address' },
          ],
          outputs: [
            { name: '', type: 'address' },
            { name: '', type: 'uint256' },
            { name: '', type: 'uint256' },
            { name: '', type: 'uint256' },
          ],
        },
        {
          stateMutability: 'nonpayable',
          type: 'function',
          name: 'repayDebt',
          inputs: [
            { name: '_paymentAsset', type: 'address' },
            { name: '_paymentAmount', type: 'uint256' },
            { name: '_recipient', type: 'address' },
            { name: '_oracleRegistry', type: 'address' },
          ],
          outputs: [
            { name: '', type: 'address' },
            { name: '', type: 'uint256' },
            { name: '', type: 'uint256' },
            { name: '', type: 'uint256' },
          ],
        },
      ],
    },
    LegoYield: {
      isTemplate: true,
      abi: [
        {
          stateMutability: 'nonpayable',
          type: 'function',
          name: 'depositTokens',
          inputs: [
            { name: '_asset', type: 'address' },
            { name: '_amount', type: 'uint256' },
            { name: '_vault', type: 'address' },
            { name: '_recipient', type: 'address' },
          ],
          outputs: [
            { name: '', type: 'uint256' },
            { name: '', type: 'address' },
            { name: '', type: 'uint256' },
            { name: '', type: 'uint256' },
            { name: '', type: 'uint256' },
          ],
        },
        {
          stateMutability: 'nonpayable',
          type: 'function',
          name: 'depositTokens',
          inputs: [
            { name: '_asset', type: 'address' },
            { name: '_amount', type: 'uint256' },
            { name: '_vault', type: 'address' },
            { name: '_recipient', type: 'address' },
            { name: '_oracleRegistry', type: 'address' },
          ],
          outputs: [
            { name: '', type: 'uint256' },
            { name: '', type: 'address' },
            { name: '', type: 'uint256' },
            { name: '', type: 'uint256' },
            { name: '', type: 'uint256' },
          ],
        },
        {
          stateMutability: 'nonpayable',
          type: 'function',
          name: 'withdrawTokens',
          inputs: [
            { name: '_asset', type: 'address' },
            { name: '_amount', type: 'uint256' },
            { name: '_vaultToken', type: 'address' },
            { name: '_recipient', type: 'address' },
          ],
          outputs: [
            { name: '', type: 'uint256' },
            { name: '', type: 'uint256' },
            { name: '', type: 'uint256' },
            { name: '', type: 'uint256' },
          ],
        },
        {
          stateMutability: 'nonpayable',
          type: 'function',
          name: 'withdrawTokens',
          inputs: [
            { name: '_asset', type: 'address' },
            { name: '_amount', type: 'uint256' },
            { name: '_vaultToken', type: 'address' },
            { name: '_recipient', type: 'address' },
            { name: '_oracleRegistry', type: 'address' },
          ],
          outputs: [
            { name: '', type: 'uint256' },
            { name: '', type: 'uint256' },
            { name: '', type: 'uint256' },
            { name: '', type: 'uint256' },
          ],
        },
        {
          stateMutability: 'view',
          type: 'function',
          name: 'getAssetOpportunities',
          inputs: [{ name: '_asset', type: 'address' }],
          outputs: [{ name: '', type: 'address[]' }],
        },
        {
          stateMutability: 'view',
          type: 'function',
          name: 'getUnderlyingAmount',
          inputs: [
            { name: '_vaultToken', type: 'address' },
            { name: '_vaultTokenAmount', type: 'uint256' },
          ],
          outputs: [{ name: '', type: 'uint256' }],
        },
        {
          stateMutability: 'view',
          type: 'function',
          name: 'getUnderlyingAsset',
          inputs: [{ name: '_vaultToken', type: 'address' }],
          outputs: [{ name: '', type: 'address' }],
        },
        {
          stateMutability: 'view',
          type: 'function',
          name: 'getAssets',
          inputs: [],
          outputs: [{ name: '', type: 'address[]' }],
        },
        {
          stateMutability: 'view',
          type: 'function',
          name: 'isVaultToken',
          inputs: [{ name: '_vaultToken', type: 'address' }],
          outputs: [{ name: '', type: 'bool' }],
        },
        {
          stateMutability: 'view',
          type: 'function',
          name: 'getVaultTokenAmount',
          inputs: [
            { name: '_asset', type: 'address' },
            { name: '_assetAmount', type: 'uint256' },
            { name: '_vaultToken', type: 'address' },
          ],
          outputs: [{ name: '', type: 'uint256' }],
        },
        {
          stateMutability: 'view',
          type: 'function',
          name: 'getUsdValueOfVaultToken',
          inputs: [
            { name: '_vaultToken', type: 'address' },
            { name: '_vaultTokenAmount', type: 'uint256' },
          ],
          outputs: [{ name: '', type: 'uint256' }],
        },
        {
          stateMutability: 'view',
          type: 'function',
          name: 'getUsdValueOfVaultToken',
          inputs: [
            { name: '_vaultToken', type: 'address' },
            { name: '_vaultTokenAmount', type: 'uint256' },
            { name: '_oracleRegistry', type: 'address' },
          ],
          outputs: [{ name: '', type: 'uint256' }],
        },
        {
          stateMutability: 'view',
          type: 'function',
          name: 'getUnderlyingData',
          inputs: [
            { name: '_vaultToken', type: 'address' },
            { name: '_vaultTokenAmount', type: 'uint256' },
          ],
          outputs: [
            { name: '', type: 'address' },
            { name: '', type: 'uint256' },
            { name: '', type: 'uint256' },
          ],
        },
        {
          stateMutability: 'view',
          type: 'function',
          name: 'getUnderlyingData',
          inputs: [
            { name: '_vaultToken', type: 'address' },
            { name: '_vaultTokenAmount', type: 'uint256' },
            { name: '_oracleRegistry', type: 'address' },
          ],
          outputs: [
            { name: '', type: 'address' },
            { name: '', type: 'uint256' },
            { name: '', type: 'uint256' },
          ],
        },
        {
          stateMutability: 'view',
          type: 'function',
          name: 'totalAssets',
          inputs: [{ name: '_vaultToken', type: 'address' }],
          outputs: [{ name: '', type: 'uint256' }],
        },
        {
          stateMutability: 'view',
          type: 'function',
          name: 'totalBorrows',
          inputs: [{ name: '_vaultToken', type: 'address' }],
          outputs: [{ name: '', type: 'uint256' }],
        },
      ],
    },
    LegoCommon: {
      isTemplate: true,
      abi: [
        {
          stateMutability: 'view',
          type: 'function',
          name: 'getRegistries',
          inputs: [],
          outputs: [{ name: '', type: 'address[]' }],
        },
        {
          stateMutability: 'view',
          type: 'function',
          name: 'getAccessForLego',
          inputs: [{ name: '_user', type: 'address' }],
          outputs: [
            { name: '', type: 'address' },
            { name: '', type: 'string' },
            { name: '', type: 'uint256' },
          ],
        },
        {
          stateMutability: 'nonpayable',
          type: 'function',
          name: 'claimRewards',
          inputs: [
            { name: '_user', type: 'address' },
            { name: '_market', type: 'address' },
            { name: '_rewardToken', type: 'address' },
            { name: '_rewardAmount', type: 'uint256' },
            { name: '_proof', type: 'bytes32' },
          ],
          outputs: [],
        },
        {
          stateMutability: 'nonpayable',
          type: 'function',
          name: 'recoverFunds',
          inputs: [
            { name: '_asset', type: 'address' },
            { name: '_recipient', type: 'address' },
          ],
          outputs: [{ name: '', type: 'bool' }],
        },
        {
          stateMutability: 'view',
          type: 'function',
          name: 'legoId',
          inputs: [],
          outputs: [{ name: '', type: 'uint256' }],
        },
        {
          stateMutability: 'nonpayable',
          type: 'function',
          name: 'setLegoId',
          inputs: [{ name: '_legoId', type: 'uint256' }],
          outputs: [{ name: '', type: 'bool' }],
        },
        {
          stateMutability: 'view',
          type: 'function',
          name: 'hasClaimableRewards',
          inputs: [{ name: '_user', type: 'address' }],
          outputs: [{ name: '', type: 'bool' }],
        },
      ],
    },
    LegoDex: {
      isTemplate: true,
      abi: [
        {
          stateMutability: 'nonpayable',
          type: 'function',
          name: 'swapTokens',
          inputs: [
            { name: '_amountIn', type: 'uint256' },
            { name: '_minAmountOut', type: 'uint256' },
            { name: '_tokenPath', type: 'address[]' },
            { name: '_poolPath', type: 'address[]' },
            { name: '_recipient', type: 'address' },
          ],
          outputs: [
            { name: '', type: 'uint256' },
            { name: '', type: 'uint256' },
            { name: '', type: 'uint256' },
            { name: '', type: 'uint256' },
          ],
        },
        {
          stateMutability: 'nonpayable',
          type: 'function',
          name: 'swapTokens',
          inputs: [
            { name: '_amountIn', type: 'uint256' },
            { name: '_minAmountOut', type: 'uint256' },
            { name: '_tokenPath', type: 'address[]' },
            { name: '_poolPath', type: 'address[]' },
            { name: '_recipient', type: 'address' },
            { name: '_oracleRegistry', type: 'address' },
          ],
          outputs: [
            { name: '', type: 'uint256' },
            { name: '', type: 'uint256' },
            { name: '', type: 'uint256' },
            { name: '', type: 'uint256' },
          ],
        },
        {
          stateMutability: 'nonpayable',
          type: 'function',
          name: 'addLiquidity',
          inputs: [
            { name: '_nftTokenId', type: 'uint256' },
            { name: '_pool', type: 'address' },
            { name: '_tokenA', type: 'address' },
            { name: '_tokenB', type: 'address' },
            { name: '_tickLower', type: 'int24' },
            { name: '_tickUpper', type: 'int24' },
            { name: '_amountA', type: 'uint256' },
            { name: '_amountB', type: 'uint256' },
            { name: '_minAmountA', type: 'uint256' },
            { name: '_minAmountB', type: 'uint256' },
            { name: '_minLpAmount', type: 'uint256' },
            { name: '_recipient', type: 'address' },
          ],
          outputs: [
            { name: '', type: 'uint256' },
            { name: '', type: 'uint256' },
            { name: '', type: 'uint256' },
            { name: '', type: 'uint256' },
            { name: '', type: 'uint256' },
            { name: '', type: 'uint256' },
            { name: '', type: 'uint256' },
          ],
        },
        {
          stateMutability: 'nonpayable',
          type: 'function',
          name: 'addLiquidity',
          inputs: [
            { name: '_nftTokenId', type: 'uint256' },
            { name: '_pool', type: 'address' },
            { name: '_tokenA', type: 'address' },
            { name: '_tokenB', type: 'address' },
            { name: '_tickLower', type: 'int24' },
            { name: '_tickUpper', type: 'int24' },
            { name: '_amountA', type: 'uint256' },
            { name: '_amountB', type: 'uint256' },
            { name: '_minAmountA', type: 'uint256' },
            { name: '_minAmountB', type: 'uint256' },
            { name: '_minLpAmount', type: 'uint256' },
            { name: '_recipient', type: 'address' },
            { name: '_oracleRegistry', type: 'address' },
          ],
          outputs: [
            { name: '', type: 'uint256' },
            { name: '', type: 'uint256' },
            { name: '', type: 'uint256' },
            { name: '', type: 'uint256' },
            { name: '', type: 'uint256' },
            { name: '', type: 'uint256' },
            { name: '', type: 'uint256' },
          ],
        },
        {
          stateMutability: 'nonpayable',
          type: 'function',
          name: 'removeLiquidity',
          inputs: [
            { name: '_nftTokenId', type: 'uint256' },
            { name: '_pool', type: 'address' },
            { name: '_tokenA', type: 'address' },
            { name: '_tokenB', type: 'address' },
            { name: '_lpToken', type: 'address' },
            { name: '_liqToRemove', type: 'uint256' },
            { name: '_minAmountA', type: 'uint256' },
            { name: '_minAmountB', type: 'uint256' },
            { name: '_recipient', type: 'address' },
          ],
          outputs: [
            { name: '', type: 'uint256' },
            { name: '', type: 'uint256' },
            { name: '', type: 'uint256' },
            { name: '', type: 'uint256' },
            { name: '', type: 'uint256' },
            { name: '', type: 'bool' },
          ],
        },
        {
          stateMutability: 'nonpayable',
          type: 'function',
          name: 'removeLiquidity',
          inputs: [
            { name: '_nftTokenId', type: 'uint256' },
            { name: '_pool', type: 'address' },
            { name: '_tokenA', type: 'address' },
            { name: '_tokenB', type: 'address' },
            { name: '_lpToken', type: 'address' },
            { name: '_liqToRemove', type: 'uint256' },
            { name: '_minAmountA', type: 'uint256' },
            { name: '_minAmountB', type: 'uint256' },
            { name: '_recipient', type: 'address' },
            { name: '_oracleRegistry', type: 'address' },
          ],
          outputs: [
            { name: '', type: 'uint256' },
            { name: '', type: 'uint256' },
            { name: '', type: 'uint256' },
            { name: '', type: 'uint256' },
            { name: '', type: 'uint256' },
            { name: '', type: 'bool' },
          ],
        },
        {
          stateMutability: 'view',
          type: 'function',
          name: 'getLpToken',
          inputs: [{ name: '_pool', type: 'address' }],
          outputs: [{ name: '', type: 'address' }],
        },
        {
          stateMutability: 'view',
          type: 'function',
          name: 'getPoolForLpToken',
          inputs: [{ name: '_lpToken', type: 'address' }],
          outputs: [{ name: '', type: 'address' }],
        },
        {
          stateMutability: 'view',
          type: 'function',
          name: 'getSwapAmountOut',
          inputs: [
            { name: '_pool', type: 'address' },
            { name: '_tokenIn', type: 'address' },
            { name: '_tokenOut', type: 'address' },
            { name: '_amountIn', type: 'uint256' },
          ],
          outputs: [{ name: '', type: 'uint256' }],
        },
        {
          stateMutability: 'view',
          type: 'function',
          name: 'getSwapAmountIn',
          inputs: [
            { name: '_pool', type: 'address' },
            { name: '_tokenIn', type: 'address' },
            { name: '_tokenOut', type: 'address' },
            { name: '_amountOut', type: 'uint256' },
          ],
          outputs: [{ name: '', type: 'uint256' }],
        },
        {
          stateMutability: 'view',
          type: 'function',
          name: 'getAddLiqAmountsIn',
          inputs: [
            { name: '_pool', type: 'address' },
            { name: '_tokenA', type: 'address' },
            { name: '_tokenB', type: 'address' },
            { name: '_availAmountA', type: 'uint256' },
            { name: '_availAmountB', type: 'uint256' },
          ],
          outputs: [
            { name: '', type: 'uint256' },
            { name: '', type: 'uint256' },
            { name: '', type: 'uint256' },
          ],
        },
        {
          stateMutability: 'view',
          type: 'function',
          name: 'getRemoveLiqAmountsOut',
          inputs: [
            { name: '_pool', type: 'address' },
            { name: '_tokenA', type: 'address' },
            { name: '_tokenB', type: 'address' },
            { name: '_lpAmount', type: 'uint256' },
          ],
          outputs: [
            { name: '', type: 'uint256' },
            { name: '', type: 'uint256' },
          ],
        },
        {
          stateMutability: 'view',
          type: 'function',
          name: 'getPriceUnsafe',
          inputs: [
            { name: '_pool', type: 'address' },
            { name: '_targetToken', type: 'address' },
          ],
          outputs: [{ name: '', type: 'uint256' }],
        },
        {
          stateMutability: 'view',
          type: 'function',
          name: 'getPriceUnsafe',
          inputs: [
            { name: '_pool', type: 'address' },
            { name: '_targetToken', type: 'address' },
            { name: '_oracleRegistry', type: 'address' },
          ],
          outputs: [{ name: '', type: 'uint256' }],
        },
        {
          stateMutability: 'view',
          type: 'function',
          name: 'getBestSwapAmountOut',
          inputs: [
            { name: '_tokenIn', type: 'address' },
            { name: '_tokenOut', type: 'address' },
            { name: '_amountIn', type: 'uint256' },
          ],
          outputs: [
            { name: '', type: 'address' },
            { name: '', type: 'uint256' },
          ],
        },
        {
          stateMutability: 'view',
          type: 'function',
          name: 'getBestSwapAmountIn',
          inputs: [
            { name: '_tokenIn', type: 'address' },
            { name: '_tokenOut', type: 'address' },
            { name: '_amountOut', type: 'uint256' },
          ],
          outputs: [
            { name: '', type: 'address' },
            { name: '', type: 'uint256' },
          ],
        },
        {
          stateMutability: 'view',
          type: 'function',
          name: 'getCoreRouterPool',
          inputs: [],
          outputs: [{ name: '', type: 'address' }],
        },
      ],
    },
    OracleParser: {
      isTemplate: true,
      abi: [
        {
          stateMutability: 'view',
          type: 'function',
          name: 'getPrice',
          inputs: [{ name: '_asset', type: 'address' }],
          outputs: [{ name: '', type: 'uint256' }],
        },
        {
          stateMutability: 'view',
          type: 'function',
          name: 'getPrice',
          inputs: [
            { name: '_asset', type: 'address' },
            { name: '_staleTime', type: 'uint256' },
          ],
          outputs: [{ name: '', type: 'uint256' }],
        },
        {
          stateMutability: 'view',
          type: 'function',
          name: 'getPrice',
          inputs: [
            { name: '_asset', type: 'address' },
            { name: '_staleTime', type: 'uint256' },
            { name: '_oracleRegistry', type: 'address' },
          ],
          outputs: [{ name: '', type: 'uint256' }],
        },
        {
          stateMutability: 'view',
          type: 'function',
          name: 'getPriceAndHasFeed',
          inputs: [{ name: '_asset', type: 'address' }],
          outputs: [
            { name: '', type: 'uint256' },
            { name: '', type: 'bool' },
          ],
        },
        {
          stateMutability: 'view',
          type: 'function',
          name: 'getPriceAndHasFeed',
          inputs: [
            { name: '_asset', type: 'address' },
            { name: '_staleTime', type: 'uint256' },
          ],
          outputs: [
            { name: '', type: 'uint256' },
            { name: '', type: 'bool' },
          ],
        },
        {
          stateMutability: 'view',
          type: 'function',
          name: 'getPriceAndHasFeed',
          inputs: [
            { name: '_asset', type: 'address' },
            { name: '_staleTime', type: 'uint256' },
            { name: '_oracleRegistry', type: 'address' },
          ],
          outputs: [
            { name: '', type: 'uint256' },
            { name: '', type: 'bool' },
          ],
        },
        {
          stateMutability: 'view',
          type: 'function',
          name: 'hasPriceFeed',
          inputs: [{ name: '_asset', type: 'address' }],
          outputs: [{ name: '', type: 'bool' }],
        },
        {
          stateMutability: 'view',
          type: 'function',
          name: 'oraclePartnerId',
          inputs: [],
          outputs: [{ name: '', type: 'uint256' }],
        },
        {
          stateMutability: 'nonpayable',
          type: 'function',
          name: 'setOraclePartnerId',
          inputs: [{ name: '_oracleId', type: 'uint256' }],
          outputs: [{ name: '', type: 'bool' }],
        },
        {
          stateMutability: 'view',
          type: 'function',
          name: 'getConfiguredAssets',
          inputs: [],
          outputs: [{ name: '', type: 'address[]' }],
        },
      ],
    },
  },
}
