/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
/* @ts-nocheck */

import { singleQuery, AddressResolverFunction } from '@dappql/async'
import { PublicClient, WalletClient } from 'viem'

type ExtractArgs<T> = T extends (...args: infer P) => any ? P : never
type Address = `0x${string}`

export const abi = [
  {
    stateMutability: 'view',
    type: 'function',
    name: 'getAddCollateralAndBorrowHash',
    inputs: [
      {
        name: '_agentSender',
        type: 'address',
      },
      {
        name: '_userWallet',
        type: 'address',
      },
      {
        name: '_debtLegoId',
        type: 'uint256',
      },
    ],
    outputs: [
      {
        name: '',
        type: 'bytes32',
      },
      {
        name: '',
        type: 'uint256',
      },
      {
        name: '',
        type: 'uint256',
      },
    ],
  },
  {
    stateMutability: 'view',
    type: 'function',
    name: 'getAddCollateralAndBorrowHash',
    inputs: [
      {
        name: '_agentSender',
        type: 'address',
      },
      {
        name: '_userWallet',
        type: 'address',
      },
      {
        name: '_debtLegoId',
        type: 'uint256',
      },
      {
        name: '_addCollateralAssets',
        type: 'tuple[]',
        components: [
          {
            name: 'vaultId',
            type: 'uint256',
          },
          {
            name: 'asset',
            type: 'address',
          },
          {
            name: 'amount',
            type: 'uint256',
          },
        ],
      },
    ],
    outputs: [
      {
        name: '',
        type: 'bytes32',
      },
      {
        name: '',
        type: 'uint256',
      },
      {
        name: '',
        type: 'uint256',
      },
    ],
  },
  {
    stateMutability: 'view',
    type: 'function',
    name: 'getAddCollateralAndBorrowHash',
    inputs: [
      {
        name: '_agentSender',
        type: 'address',
      },
      {
        name: '_userWallet',
        type: 'address',
      },
      {
        name: '_debtLegoId',
        type: 'uint256',
      },
      {
        name: '_addCollateralAssets',
        type: 'tuple[]',
        components: [
          {
            name: 'vaultId',
            type: 'uint256',
          },
          {
            name: 'asset',
            type: 'address',
          },
          {
            name: 'amount',
            type: 'uint256',
          },
        ],
      },
      {
        name: '_greenBorrowAmount',
        type: 'uint256',
      },
    ],
    outputs: [
      {
        name: '',
        type: 'bytes32',
      },
      {
        name: '',
        type: 'uint256',
      },
      {
        name: '',
        type: 'uint256',
      },
    ],
  },
  {
    stateMutability: 'view',
    type: 'function',
    name: 'getAddCollateralAndBorrowHash',
    inputs: [
      {
        name: '_agentSender',
        type: 'address',
      },
      {
        name: '_userWallet',
        type: 'address',
      },
      {
        name: '_debtLegoId',
        type: 'uint256',
      },
      {
        name: '_addCollateralAssets',
        type: 'tuple[]',
        components: [
          {
            name: 'vaultId',
            type: 'uint256',
          },
          {
            name: 'asset',
            type: 'address',
          },
          {
            name: 'amount',
            type: 'uint256',
          },
        ],
      },
      {
        name: '_greenBorrowAmount',
        type: 'uint256',
      },
      {
        name: '_wantsSavingsGreen',
        type: 'bool',
      },
    ],
    outputs: [
      {
        name: '',
        type: 'bytes32',
      },
      {
        name: '',
        type: 'uint256',
      },
      {
        name: '',
        type: 'uint256',
      },
    ],
  },
  {
    stateMutability: 'view',
    type: 'function',
    name: 'getAddCollateralAndBorrowHash',
    inputs: [
      {
        name: '_agentSender',
        type: 'address',
      },
      {
        name: '_userWallet',
        type: 'address',
      },
      {
        name: '_debtLegoId',
        type: 'uint256',
      },
      {
        name: '_addCollateralAssets',
        type: 'tuple[]',
        components: [
          {
            name: 'vaultId',
            type: 'uint256',
          },
          {
            name: 'asset',
            type: 'address',
          },
          {
            name: 'amount',
            type: 'uint256',
          },
        ],
      },
      {
        name: '_greenBorrowAmount',
        type: 'uint256',
      },
      {
        name: '_wantsSavingsGreen',
        type: 'bool',
      },
      {
        name: '_shouldEnterStabPool',
        type: 'bool',
      },
    ],
    outputs: [
      {
        name: '',
        type: 'bytes32',
      },
      {
        name: '',
        type: 'uint256',
      },
      {
        name: '',
        type: 'uint256',
      },
    ],
  },
  {
    stateMutability: 'view',
    type: 'function',
    name: 'getAddCollateralAndBorrowHash',
    inputs: [
      {
        name: '_agentSender',
        type: 'address',
      },
      {
        name: '_userWallet',
        type: 'address',
      },
      {
        name: '_debtLegoId',
        type: 'uint256',
      },
      {
        name: '_addCollateralAssets',
        type: 'tuple[]',
        components: [
          {
            name: 'vaultId',
            type: 'uint256',
          },
          {
            name: 'asset',
            type: 'address',
          },
          {
            name: 'amount',
            type: 'uint256',
          },
        ],
      },
      {
        name: '_greenBorrowAmount',
        type: 'uint256',
      },
      {
        name: '_wantsSavingsGreen',
        type: 'bool',
      },
      {
        name: '_shouldEnterStabPool',
        type: 'bool',
      },
      {
        name: '_swapInstructions',
        type: 'tuple[]',
        components: [
          {
            name: 'legoId',
            type: 'uint256',
          },
          {
            name: 'amountIn',
            type: 'uint256',
          },
          {
            name: 'minAmountOut',
            type: 'uint256',
          },
          {
            name: 'tokenPath',
            type: 'address[]',
          },
          {
            name: 'poolPath',
            type: 'address[]',
          },
        ],
      },
    ],
    outputs: [
      {
        name: '',
        type: 'bytes32',
      },
      {
        name: '',
        type: 'uint256',
      },
      {
        name: '',
        type: 'uint256',
      },
    ],
  },
  {
    stateMutability: 'view',
    type: 'function',
    name: 'getAddCollateralAndBorrowHash',
    inputs: [
      {
        name: '_agentSender',
        type: 'address',
      },
      {
        name: '_userWallet',
        type: 'address',
      },
      {
        name: '_debtLegoId',
        type: 'uint256',
      },
      {
        name: '_addCollateralAssets',
        type: 'tuple[]',
        components: [
          {
            name: 'vaultId',
            type: 'uint256',
          },
          {
            name: 'asset',
            type: 'address',
          },
          {
            name: 'amount',
            type: 'uint256',
          },
        ],
      },
      {
        name: '_greenBorrowAmount',
        type: 'uint256',
      },
      {
        name: '_wantsSavingsGreen',
        type: 'bool',
      },
      {
        name: '_shouldEnterStabPool',
        type: 'bool',
      },
      {
        name: '_swapInstructions',
        type: 'tuple[]',
        components: [
          {
            name: 'legoId',
            type: 'uint256',
          },
          {
            name: 'amountIn',
            type: 'uint256',
          },
          {
            name: 'minAmountOut',
            type: 'uint256',
          },
          {
            name: 'tokenPath',
            type: 'address[]',
          },
          {
            name: 'poolPath',
            type: 'address[]',
          },
        ],
      },
      {
        name: '_yieldPosition',
        type: 'tuple',
        components: [
          {
            name: 'legoId',
            type: 'uint256',
          },
          {
            name: 'asset',
            type: 'address',
          },
          {
            name: 'amount',
            type: 'uint256',
          },
          {
            name: 'vaultAddr',
            type: 'address',
          },
        ],
      },
    ],
    outputs: [
      {
        name: '',
        type: 'bytes32',
      },
      {
        name: '',
        type: 'uint256',
      },
      {
        name: '',
        type: 'uint256',
      },
    ],
  },
  {
    stateMutability: 'view',
    type: 'function',
    name: 'getAddCollateralAndBorrowHash',
    inputs: [
      {
        name: '_agentSender',
        type: 'address',
      },
      {
        name: '_userWallet',
        type: 'address',
      },
      {
        name: '_debtLegoId',
        type: 'uint256',
      },
      {
        name: '_addCollateralAssets',
        type: 'tuple[]',
        components: [
          {
            name: 'vaultId',
            type: 'uint256',
          },
          {
            name: 'asset',
            type: 'address',
          },
          {
            name: 'amount',
            type: 'uint256',
          },
        ],
      },
      {
        name: '_greenBorrowAmount',
        type: 'uint256',
      },
      {
        name: '_wantsSavingsGreen',
        type: 'bool',
      },
      {
        name: '_shouldEnterStabPool',
        type: 'bool',
      },
      {
        name: '_swapInstructions',
        type: 'tuple[]',
        components: [
          {
            name: 'legoId',
            type: 'uint256',
          },
          {
            name: 'amountIn',
            type: 'uint256',
          },
          {
            name: 'minAmountOut',
            type: 'uint256',
          },
          {
            name: 'tokenPath',
            type: 'address[]',
          },
          {
            name: 'poolPath',
            type: 'address[]',
          },
        ],
      },
      {
        name: '_yieldPosition',
        type: 'tuple',
        components: [
          {
            name: 'legoId',
            type: 'uint256',
          },
          {
            name: 'asset',
            type: 'address',
          },
          {
            name: 'amount',
            type: 'uint256',
          },
          {
            name: 'vaultAddr',
            type: 'address',
          },
        ],
      },
      {
        name: '_nonce',
        type: 'uint256',
      },
    ],
    outputs: [
      {
        name: '',
        type: 'bytes32',
      },
      {
        name: '',
        type: 'uint256',
      },
      {
        name: '',
        type: 'uint256',
      },
    ],
  },
  {
    stateMutability: 'view',
    type: 'function',
    name: 'getAddCollateralAndBorrowHash',
    inputs: [
      {
        name: '_agentSender',
        type: 'address',
      },
      {
        name: '_userWallet',
        type: 'address',
      },
      {
        name: '_debtLegoId',
        type: 'uint256',
      },
      {
        name: '_addCollateralAssets',
        type: 'tuple[]',
        components: [
          {
            name: 'vaultId',
            type: 'uint256',
          },
          {
            name: 'asset',
            type: 'address',
          },
          {
            name: 'amount',
            type: 'uint256',
          },
        ],
      },
      {
        name: '_greenBorrowAmount',
        type: 'uint256',
      },
      {
        name: '_wantsSavingsGreen',
        type: 'bool',
      },
      {
        name: '_shouldEnterStabPool',
        type: 'bool',
      },
      {
        name: '_swapInstructions',
        type: 'tuple[]',
        components: [
          {
            name: 'legoId',
            type: 'uint256',
          },
          {
            name: 'amountIn',
            type: 'uint256',
          },
          {
            name: 'minAmountOut',
            type: 'uint256',
          },
          {
            name: 'tokenPath',
            type: 'address[]',
          },
          {
            name: 'poolPath',
            type: 'address[]',
          },
        ],
      },
      {
        name: '_yieldPosition',
        type: 'tuple',
        components: [
          {
            name: 'legoId',
            type: 'uint256',
          },
          {
            name: 'asset',
            type: 'address',
          },
          {
            name: 'amount',
            type: 'uint256',
          },
          {
            name: 'vaultAddr',
            type: 'address',
          },
        ],
      },
      {
        name: '_nonce',
        type: 'uint256',
      },
      {
        name: '_expiration',
        type: 'uint256',
      },
    ],
    outputs: [
      {
        name: '',
        type: 'bytes32',
      },
      {
        name: '',
        type: 'uint256',
      },
      {
        name: '',
        type: 'uint256',
      },
    ],
  },
  {
    stateMutability: 'view',
    type: 'function',
    name: 'getRepayAndWithdrawHash',
    inputs: [
      {
        name: '_agentSender',
        type: 'address',
      },
      {
        name: '_userWallet',
        type: 'address',
      },
      {
        name: '_debtLegoId',
        type: 'uint256',
      },
    ],
    outputs: [
      {
        name: '',
        type: 'bytes32',
      },
      {
        name: '',
        type: 'uint256',
      },
      {
        name: '',
        type: 'uint256',
      },
    ],
  },
  {
    stateMutability: 'view',
    type: 'function',
    name: 'getRepayAndWithdrawHash',
    inputs: [
      {
        name: '_agentSender',
        type: 'address',
      },
      {
        name: '_userWallet',
        type: 'address',
      },
      {
        name: '_debtLegoId',
        type: 'uint256',
      },
      {
        name: '_deleverageAssets',
        type: 'tuple[]',
        components: [
          {
            name: 'vaultId',
            type: 'uint256',
          },
          {
            name: 'asset',
            type: 'address',
          },
          {
            name: 'targetRepayAmount',
            type: 'uint256',
          },
        ],
      },
    ],
    outputs: [
      {
        name: '',
        type: 'bytes32',
      },
      {
        name: '',
        type: 'uint256',
      },
      {
        name: '',
        type: 'uint256',
      },
    ],
  },
  {
    stateMutability: 'view',
    type: 'function',
    name: 'getRepayAndWithdrawHash',
    inputs: [
      {
        name: '_agentSender',
        type: 'address',
      },
      {
        name: '_userWallet',
        type: 'address',
      },
      {
        name: '_debtLegoId',
        type: 'uint256',
      },
      {
        name: '_deleverageAssets',
        type: 'tuple[]',
        components: [
          {
            name: 'vaultId',
            type: 'uint256',
          },
          {
            name: 'asset',
            type: 'address',
          },
          {
            name: 'targetRepayAmount',
            type: 'uint256',
          },
        ],
      },
      {
        name: '_yieldPosition',
        type: 'tuple',
        components: [
          {
            name: 'legoId',
            type: 'uint256',
          },
          {
            name: 'vaultToken',
            type: 'address',
          },
          {
            name: 'vaultTokenAmount',
            type: 'uint256',
          },
        ],
      },
    ],
    outputs: [
      {
        name: '',
        type: 'bytes32',
      },
      {
        name: '',
        type: 'uint256',
      },
      {
        name: '',
        type: 'uint256',
      },
    ],
  },
  {
    stateMutability: 'view',
    type: 'function',
    name: 'getRepayAndWithdrawHash',
    inputs: [
      {
        name: '_agentSender',
        type: 'address',
      },
      {
        name: '_userWallet',
        type: 'address',
      },
      {
        name: '_debtLegoId',
        type: 'uint256',
      },
      {
        name: '_deleverageAssets',
        type: 'tuple[]',
        components: [
          {
            name: 'vaultId',
            type: 'uint256',
          },
          {
            name: 'asset',
            type: 'address',
          },
          {
            name: 'targetRepayAmount',
            type: 'uint256',
          },
        ],
      },
      {
        name: '_yieldPosition',
        type: 'tuple',
        components: [
          {
            name: 'legoId',
            type: 'uint256',
          },
          {
            name: 'vaultToken',
            type: 'address',
          },
          {
            name: 'vaultTokenAmount',
            type: 'uint256',
          },
        ],
      },
      {
        name: '_swapInstructions',
        type: 'tuple[]',
        components: [
          {
            name: 'legoId',
            type: 'uint256',
          },
          {
            name: 'amountIn',
            type: 'uint256',
          },
          {
            name: 'minAmountOut',
            type: 'uint256',
          },
          {
            name: 'tokenPath',
            type: 'address[]',
          },
          {
            name: 'poolPath',
            type: 'address[]',
          },
        ],
      },
    ],
    outputs: [
      {
        name: '',
        type: 'bytes32',
      },
      {
        name: '',
        type: 'uint256',
      },
      {
        name: '',
        type: 'uint256',
      },
    ],
  },
  {
    stateMutability: 'view',
    type: 'function',
    name: 'getRepayAndWithdrawHash',
    inputs: [
      {
        name: '_agentSender',
        type: 'address',
      },
      {
        name: '_userWallet',
        type: 'address',
      },
      {
        name: '_debtLegoId',
        type: 'uint256',
      },
      {
        name: '_deleverageAssets',
        type: 'tuple[]',
        components: [
          {
            name: 'vaultId',
            type: 'uint256',
          },
          {
            name: 'asset',
            type: 'address',
          },
          {
            name: 'targetRepayAmount',
            type: 'uint256',
          },
        ],
      },
      {
        name: '_yieldPosition',
        type: 'tuple',
        components: [
          {
            name: 'legoId',
            type: 'uint256',
          },
          {
            name: 'vaultToken',
            type: 'address',
          },
          {
            name: 'vaultTokenAmount',
            type: 'uint256',
          },
        ],
      },
      {
        name: '_swapInstructions',
        type: 'tuple[]',
        components: [
          {
            name: 'legoId',
            type: 'uint256',
          },
          {
            name: 'amountIn',
            type: 'uint256',
          },
          {
            name: 'minAmountOut',
            type: 'uint256',
          },
          {
            name: 'tokenPath',
            type: 'address[]',
          },
          {
            name: 'poolPath',
            type: 'address[]',
          },
        ],
      },
      {
        name: '_repayAsset',
        type: 'address',
      },
    ],
    outputs: [
      {
        name: '',
        type: 'bytes32',
      },
      {
        name: '',
        type: 'uint256',
      },
      {
        name: '',
        type: 'uint256',
      },
    ],
  },
  {
    stateMutability: 'view',
    type: 'function',
    name: 'getRepayAndWithdrawHash',
    inputs: [
      {
        name: '_agentSender',
        type: 'address',
      },
      {
        name: '_userWallet',
        type: 'address',
      },
      {
        name: '_debtLegoId',
        type: 'uint256',
      },
      {
        name: '_deleverageAssets',
        type: 'tuple[]',
        components: [
          {
            name: 'vaultId',
            type: 'uint256',
          },
          {
            name: 'asset',
            type: 'address',
          },
          {
            name: 'targetRepayAmount',
            type: 'uint256',
          },
        ],
      },
      {
        name: '_yieldPosition',
        type: 'tuple',
        components: [
          {
            name: 'legoId',
            type: 'uint256',
          },
          {
            name: 'vaultToken',
            type: 'address',
          },
          {
            name: 'vaultTokenAmount',
            type: 'uint256',
          },
        ],
      },
      {
        name: '_swapInstructions',
        type: 'tuple[]',
        components: [
          {
            name: 'legoId',
            type: 'uint256',
          },
          {
            name: 'amountIn',
            type: 'uint256',
          },
          {
            name: 'minAmountOut',
            type: 'uint256',
          },
          {
            name: 'tokenPath',
            type: 'address[]',
          },
          {
            name: 'poolPath',
            type: 'address[]',
          },
        ],
      },
      {
        name: '_repayAsset',
        type: 'address',
      },
      {
        name: '_repayAmount',
        type: 'uint256',
      },
    ],
    outputs: [
      {
        name: '',
        type: 'bytes32',
      },
      {
        name: '',
        type: 'uint256',
      },
      {
        name: '',
        type: 'uint256',
      },
    ],
  },
  {
    stateMutability: 'view',
    type: 'function',
    name: 'getRepayAndWithdrawHash',
    inputs: [
      {
        name: '_agentSender',
        type: 'address',
      },
      {
        name: '_userWallet',
        type: 'address',
      },
      {
        name: '_debtLegoId',
        type: 'uint256',
      },
      {
        name: '_deleverageAssets',
        type: 'tuple[]',
        components: [
          {
            name: 'vaultId',
            type: 'uint256',
          },
          {
            name: 'asset',
            type: 'address',
          },
          {
            name: 'targetRepayAmount',
            type: 'uint256',
          },
        ],
      },
      {
        name: '_yieldPosition',
        type: 'tuple',
        components: [
          {
            name: 'legoId',
            type: 'uint256',
          },
          {
            name: 'vaultToken',
            type: 'address',
          },
          {
            name: 'vaultTokenAmount',
            type: 'uint256',
          },
        ],
      },
      {
        name: '_swapInstructions',
        type: 'tuple[]',
        components: [
          {
            name: 'legoId',
            type: 'uint256',
          },
          {
            name: 'amountIn',
            type: 'uint256',
          },
          {
            name: 'minAmountOut',
            type: 'uint256',
          },
          {
            name: 'tokenPath',
            type: 'address[]',
          },
          {
            name: 'poolPath',
            type: 'address[]',
          },
        ],
      },
      {
        name: '_repayAsset',
        type: 'address',
      },
      {
        name: '_repayAmount',
        type: 'uint256',
      },
      {
        name: '_removeCollateralAssets',
        type: 'tuple[]',
        components: [
          {
            name: 'vaultId',
            type: 'uint256',
          },
          {
            name: 'asset',
            type: 'address',
          },
          {
            name: 'amount',
            type: 'uint256',
          },
        ],
      },
    ],
    outputs: [
      {
        name: '',
        type: 'bytes32',
      },
      {
        name: '',
        type: 'uint256',
      },
      {
        name: '',
        type: 'uint256',
      },
    ],
  },
  {
    stateMutability: 'view',
    type: 'function',
    name: 'getRepayAndWithdrawHash',
    inputs: [
      {
        name: '_agentSender',
        type: 'address',
      },
      {
        name: '_userWallet',
        type: 'address',
      },
      {
        name: '_debtLegoId',
        type: 'uint256',
      },
      {
        name: '_deleverageAssets',
        type: 'tuple[]',
        components: [
          {
            name: 'vaultId',
            type: 'uint256',
          },
          {
            name: 'asset',
            type: 'address',
          },
          {
            name: 'targetRepayAmount',
            type: 'uint256',
          },
        ],
      },
      {
        name: '_yieldPosition',
        type: 'tuple',
        components: [
          {
            name: 'legoId',
            type: 'uint256',
          },
          {
            name: 'vaultToken',
            type: 'address',
          },
          {
            name: 'vaultTokenAmount',
            type: 'uint256',
          },
        ],
      },
      {
        name: '_swapInstructions',
        type: 'tuple[]',
        components: [
          {
            name: 'legoId',
            type: 'uint256',
          },
          {
            name: 'amountIn',
            type: 'uint256',
          },
          {
            name: 'minAmountOut',
            type: 'uint256',
          },
          {
            name: 'tokenPath',
            type: 'address[]',
          },
          {
            name: 'poolPath',
            type: 'address[]',
          },
        ],
      },
      {
        name: '_repayAsset',
        type: 'address',
      },
      {
        name: '_repayAmount',
        type: 'uint256',
      },
      {
        name: '_removeCollateralAssets',
        type: 'tuple[]',
        components: [
          {
            name: 'vaultId',
            type: 'uint256',
          },
          {
            name: 'asset',
            type: 'address',
          },
          {
            name: 'amount',
            type: 'uint256',
          },
        ],
      },
      {
        name: '_nonce',
        type: 'uint256',
      },
    ],
    outputs: [
      {
        name: '',
        type: 'bytes32',
      },
      {
        name: '',
        type: 'uint256',
      },
      {
        name: '',
        type: 'uint256',
      },
    ],
  },
  {
    stateMutability: 'view',
    type: 'function',
    name: 'getRepayAndWithdrawHash',
    inputs: [
      {
        name: '_agentSender',
        type: 'address',
      },
      {
        name: '_userWallet',
        type: 'address',
      },
      {
        name: '_debtLegoId',
        type: 'uint256',
      },
      {
        name: '_deleverageAssets',
        type: 'tuple[]',
        components: [
          {
            name: 'vaultId',
            type: 'uint256',
          },
          {
            name: 'asset',
            type: 'address',
          },
          {
            name: 'targetRepayAmount',
            type: 'uint256',
          },
        ],
      },
      {
        name: '_yieldPosition',
        type: 'tuple',
        components: [
          {
            name: 'legoId',
            type: 'uint256',
          },
          {
            name: 'vaultToken',
            type: 'address',
          },
          {
            name: 'vaultTokenAmount',
            type: 'uint256',
          },
        ],
      },
      {
        name: '_swapInstructions',
        type: 'tuple[]',
        components: [
          {
            name: 'legoId',
            type: 'uint256',
          },
          {
            name: 'amountIn',
            type: 'uint256',
          },
          {
            name: 'minAmountOut',
            type: 'uint256',
          },
          {
            name: 'tokenPath',
            type: 'address[]',
          },
          {
            name: 'poolPath',
            type: 'address[]',
          },
        ],
      },
      {
        name: '_repayAsset',
        type: 'address',
      },
      {
        name: '_repayAmount',
        type: 'uint256',
      },
      {
        name: '_removeCollateralAssets',
        type: 'tuple[]',
        components: [
          {
            name: 'vaultId',
            type: 'uint256',
          },
          {
            name: 'asset',
            type: 'address',
          },
          {
            name: 'amount',
            type: 'uint256',
          },
        ],
      },
      {
        name: '_nonce',
        type: 'uint256',
      },
      {
        name: '_expiration',
        type: 'uint256',
      },
    ],
    outputs: [
      {
        name: '',
        type: 'bytes32',
      },
      {
        name: '',
        type: 'uint256',
      },
      {
        name: '',
        type: 'uint256',
      },
    ],
  },
  {
    stateMutability: 'view',
    type: 'function',
    name: 'getRebalanceYieldPositionsWithSwapHash',
    inputs: [
      {
        name: '_agentSender',
        type: 'address',
      },
      {
        name: '_userWallet',
        type: 'address',
      },
    ],
    outputs: [
      {
        name: '',
        type: 'bytes32',
      },
      {
        name: '',
        type: 'uint256',
      },
      {
        name: '',
        type: 'uint256',
      },
    ],
  },
  {
    stateMutability: 'view',
    type: 'function',
    name: 'getRebalanceYieldPositionsWithSwapHash',
    inputs: [
      {
        name: '_agentSender',
        type: 'address',
      },
      {
        name: '_userWallet',
        type: 'address',
      },
      {
        name: '_withdrawFrom',
        type: 'tuple[]',
        components: [
          {
            name: 'legoId',
            type: 'uint256',
          },
          {
            name: 'vaultToken',
            type: 'address',
          },
          {
            name: 'vaultTokenAmount',
            type: 'uint256',
          },
        ],
      },
    ],
    outputs: [
      {
        name: '',
        type: 'bytes32',
      },
      {
        name: '',
        type: 'uint256',
      },
      {
        name: '',
        type: 'uint256',
      },
    ],
  },
  {
    stateMutability: 'view',
    type: 'function',
    name: 'getRebalanceYieldPositionsWithSwapHash',
    inputs: [
      {
        name: '_agentSender',
        type: 'address',
      },
      {
        name: '_userWallet',
        type: 'address',
      },
      {
        name: '_withdrawFrom',
        type: 'tuple[]',
        components: [
          {
            name: 'legoId',
            type: 'uint256',
          },
          {
            name: 'vaultToken',
            type: 'address',
          },
          {
            name: 'vaultTokenAmount',
            type: 'uint256',
          },
        ],
      },
      {
        name: '_swapInstructions',
        type: 'tuple[]',
        components: [
          {
            name: 'legoId',
            type: 'uint256',
          },
          {
            name: 'amountIn',
            type: 'uint256',
          },
          {
            name: 'minAmountOut',
            type: 'uint256',
          },
          {
            name: 'tokenPath',
            type: 'address[]',
          },
          {
            name: 'poolPath',
            type: 'address[]',
          },
        ],
      },
    ],
    outputs: [
      {
        name: '',
        type: 'bytes32',
      },
      {
        name: '',
        type: 'uint256',
      },
      {
        name: '',
        type: 'uint256',
      },
    ],
  },
  {
    stateMutability: 'view',
    type: 'function',
    name: 'getRebalanceYieldPositionsWithSwapHash',
    inputs: [
      {
        name: '_agentSender',
        type: 'address',
      },
      {
        name: '_userWallet',
        type: 'address',
      },
      {
        name: '_withdrawFrom',
        type: 'tuple[]',
        components: [
          {
            name: 'legoId',
            type: 'uint256',
          },
          {
            name: 'vaultToken',
            type: 'address',
          },
          {
            name: 'vaultTokenAmount',
            type: 'uint256',
          },
        ],
      },
      {
        name: '_swapInstructions',
        type: 'tuple[]',
        components: [
          {
            name: 'legoId',
            type: 'uint256',
          },
          {
            name: 'amountIn',
            type: 'uint256',
          },
          {
            name: 'minAmountOut',
            type: 'uint256',
          },
          {
            name: 'tokenPath',
            type: 'address[]',
          },
          {
            name: 'poolPath',
            type: 'address[]',
          },
        ],
      },
      {
        name: '_depositTo',
        type: 'tuple[]',
        components: [
          {
            name: 'legoId',
            type: 'uint256',
          },
          {
            name: 'asset',
            type: 'address',
          },
          {
            name: 'amount',
            type: 'uint256',
          },
          {
            name: 'vaultAddr',
            type: 'address',
          },
        ],
      },
    ],
    outputs: [
      {
        name: '',
        type: 'bytes32',
      },
      {
        name: '',
        type: 'uint256',
      },
      {
        name: '',
        type: 'uint256',
      },
    ],
  },
  {
    stateMutability: 'view',
    type: 'function',
    name: 'getRebalanceYieldPositionsWithSwapHash',
    inputs: [
      {
        name: '_agentSender',
        type: 'address',
      },
      {
        name: '_userWallet',
        type: 'address',
      },
      {
        name: '_withdrawFrom',
        type: 'tuple[]',
        components: [
          {
            name: 'legoId',
            type: 'uint256',
          },
          {
            name: 'vaultToken',
            type: 'address',
          },
          {
            name: 'vaultTokenAmount',
            type: 'uint256',
          },
        ],
      },
      {
        name: '_swapInstructions',
        type: 'tuple[]',
        components: [
          {
            name: 'legoId',
            type: 'uint256',
          },
          {
            name: 'amountIn',
            type: 'uint256',
          },
          {
            name: 'minAmountOut',
            type: 'uint256',
          },
          {
            name: 'tokenPath',
            type: 'address[]',
          },
          {
            name: 'poolPath',
            type: 'address[]',
          },
        ],
      },
      {
        name: '_depositTo',
        type: 'tuple[]',
        components: [
          {
            name: 'legoId',
            type: 'uint256',
          },
          {
            name: 'asset',
            type: 'address',
          },
          {
            name: 'amount',
            type: 'uint256',
          },
          {
            name: 'vaultAddr',
            type: 'address',
          },
        ],
      },
      {
        name: '_transferTo',
        type: 'tuple[]',
        components: [
          {
            name: 'asset',
            type: 'address',
          },
          {
            name: 'amount',
            type: 'uint256',
          },
          {
            name: 'recipient',
            type: 'address',
          },
        ],
      },
    ],
    outputs: [
      {
        name: '',
        type: 'bytes32',
      },
      {
        name: '',
        type: 'uint256',
      },
      {
        name: '',
        type: 'uint256',
      },
    ],
  },
  {
    stateMutability: 'view',
    type: 'function',
    name: 'getRebalanceYieldPositionsWithSwapHash',
    inputs: [
      {
        name: '_agentSender',
        type: 'address',
      },
      {
        name: '_userWallet',
        type: 'address',
      },
      {
        name: '_withdrawFrom',
        type: 'tuple[]',
        components: [
          {
            name: 'legoId',
            type: 'uint256',
          },
          {
            name: 'vaultToken',
            type: 'address',
          },
          {
            name: 'vaultTokenAmount',
            type: 'uint256',
          },
        ],
      },
      {
        name: '_swapInstructions',
        type: 'tuple[]',
        components: [
          {
            name: 'legoId',
            type: 'uint256',
          },
          {
            name: 'amountIn',
            type: 'uint256',
          },
          {
            name: 'minAmountOut',
            type: 'uint256',
          },
          {
            name: 'tokenPath',
            type: 'address[]',
          },
          {
            name: 'poolPath',
            type: 'address[]',
          },
        ],
      },
      {
        name: '_depositTo',
        type: 'tuple[]',
        components: [
          {
            name: 'legoId',
            type: 'uint256',
          },
          {
            name: 'asset',
            type: 'address',
          },
          {
            name: 'amount',
            type: 'uint256',
          },
          {
            name: 'vaultAddr',
            type: 'address',
          },
        ],
      },
      {
        name: '_transferTo',
        type: 'tuple[]',
        components: [
          {
            name: 'asset',
            type: 'address',
          },
          {
            name: 'amount',
            type: 'uint256',
          },
          {
            name: 'recipient',
            type: 'address',
          },
        ],
      },
      {
        name: '_nonce',
        type: 'uint256',
      },
    ],
    outputs: [
      {
        name: '',
        type: 'bytes32',
      },
      {
        name: '',
        type: 'uint256',
      },
      {
        name: '',
        type: 'uint256',
      },
    ],
  },
  {
    stateMutability: 'view',
    type: 'function',
    name: 'getRebalanceYieldPositionsWithSwapHash',
    inputs: [
      {
        name: '_agentSender',
        type: 'address',
      },
      {
        name: '_userWallet',
        type: 'address',
      },
      {
        name: '_withdrawFrom',
        type: 'tuple[]',
        components: [
          {
            name: 'legoId',
            type: 'uint256',
          },
          {
            name: 'vaultToken',
            type: 'address',
          },
          {
            name: 'vaultTokenAmount',
            type: 'uint256',
          },
        ],
      },
      {
        name: '_swapInstructions',
        type: 'tuple[]',
        components: [
          {
            name: 'legoId',
            type: 'uint256',
          },
          {
            name: 'amountIn',
            type: 'uint256',
          },
          {
            name: 'minAmountOut',
            type: 'uint256',
          },
          {
            name: 'tokenPath',
            type: 'address[]',
          },
          {
            name: 'poolPath',
            type: 'address[]',
          },
        ],
      },
      {
        name: '_depositTo',
        type: 'tuple[]',
        components: [
          {
            name: 'legoId',
            type: 'uint256',
          },
          {
            name: 'asset',
            type: 'address',
          },
          {
            name: 'amount',
            type: 'uint256',
          },
          {
            name: 'vaultAddr',
            type: 'address',
          },
        ],
      },
      {
        name: '_transferTo',
        type: 'tuple[]',
        components: [
          {
            name: 'asset',
            type: 'address',
          },
          {
            name: 'amount',
            type: 'uint256',
          },
          {
            name: 'recipient',
            type: 'address',
          },
        ],
      },
      {
        name: '_nonce',
        type: 'uint256',
      },
      {
        name: '_expiration',
        type: 'uint256',
      },
    ],
    outputs: [
      {
        name: '',
        type: 'bytes32',
      },
      {
        name: '',
        type: 'uint256',
      },
      {
        name: '',
        type: 'uint256',
      },
    ],
  },
  {
    stateMutability: 'view',
    type: 'function',
    name: 'getClaimIncentivesAndSwapHash',
    inputs: [
      {
        name: '_agentSender',
        type: 'address',
      },
      {
        name: '_userWallet',
        type: 'address',
      },
    ],
    outputs: [
      {
        name: '',
        type: 'bytes32',
      },
      {
        name: '',
        type: 'uint256',
      },
      {
        name: '',
        type: 'uint256',
      },
    ],
  },
  {
    stateMutability: 'view',
    type: 'function',
    name: 'getClaimIncentivesAndSwapHash',
    inputs: [
      {
        name: '_agentSender',
        type: 'address',
      },
      {
        name: '_userWallet',
        type: 'address',
      },
      {
        name: '_rewardLegoId',
        type: 'uint256',
      },
    ],
    outputs: [
      {
        name: '',
        type: 'bytes32',
      },
      {
        name: '',
        type: 'uint256',
      },
      {
        name: '',
        type: 'uint256',
      },
    ],
  },
  {
    stateMutability: 'view',
    type: 'function',
    name: 'getClaimIncentivesAndSwapHash',
    inputs: [
      {
        name: '_agentSender',
        type: 'address',
      },
      {
        name: '_userWallet',
        type: 'address',
      },
      {
        name: '_rewardLegoId',
        type: 'uint256',
      },
      {
        name: '_rewardToken',
        type: 'address',
      },
    ],
    outputs: [
      {
        name: '',
        type: 'bytes32',
      },
      {
        name: '',
        type: 'uint256',
      },
      {
        name: '',
        type: 'uint256',
      },
    ],
  },
  {
    stateMutability: 'view',
    type: 'function',
    name: 'getClaimIncentivesAndSwapHash',
    inputs: [
      {
        name: '_agentSender',
        type: 'address',
      },
      {
        name: '_userWallet',
        type: 'address',
      },
      {
        name: '_rewardLegoId',
        type: 'uint256',
      },
      {
        name: '_rewardToken',
        type: 'address',
      },
      {
        name: '_rewardAmount',
        type: 'uint256',
      },
    ],
    outputs: [
      {
        name: '',
        type: 'bytes32',
      },
      {
        name: '',
        type: 'uint256',
      },
      {
        name: '',
        type: 'uint256',
      },
    ],
  },
  {
    stateMutability: 'view',
    type: 'function',
    name: 'getClaimIncentivesAndSwapHash',
    inputs: [
      {
        name: '_agentSender',
        type: 'address',
      },
      {
        name: '_userWallet',
        type: 'address',
      },
      {
        name: '_rewardLegoId',
        type: 'uint256',
      },
      {
        name: '_rewardToken',
        type: 'address',
      },
      {
        name: '_rewardAmount',
        type: 'uint256',
      },
      {
        name: '_rewardProofs',
        type: 'bytes32[]',
      },
    ],
    outputs: [
      {
        name: '',
        type: 'bytes32',
      },
      {
        name: '',
        type: 'uint256',
      },
      {
        name: '',
        type: 'uint256',
      },
    ],
  },
  {
    stateMutability: 'view',
    type: 'function',
    name: 'getClaimIncentivesAndSwapHash',
    inputs: [
      {
        name: '_agentSender',
        type: 'address',
      },
      {
        name: '_userWallet',
        type: 'address',
      },
      {
        name: '_rewardLegoId',
        type: 'uint256',
      },
      {
        name: '_rewardToken',
        type: 'address',
      },
      {
        name: '_rewardAmount',
        type: 'uint256',
      },
      {
        name: '_rewardProofs',
        type: 'bytes32[]',
      },
      {
        name: '_swapInstructions',
        type: 'tuple[]',
        components: [
          {
            name: 'legoId',
            type: 'uint256',
          },
          {
            name: 'amountIn',
            type: 'uint256',
          },
          {
            name: 'minAmountOut',
            type: 'uint256',
          },
          {
            name: 'tokenPath',
            type: 'address[]',
          },
          {
            name: 'poolPath',
            type: 'address[]',
          },
        ],
      },
    ],
    outputs: [
      {
        name: '',
        type: 'bytes32',
      },
      {
        name: '',
        type: 'uint256',
      },
      {
        name: '',
        type: 'uint256',
      },
    ],
  },
  {
    stateMutability: 'view',
    type: 'function',
    name: 'getClaimIncentivesAndSwapHash',
    inputs: [
      {
        name: '_agentSender',
        type: 'address',
      },
      {
        name: '_userWallet',
        type: 'address',
      },
      {
        name: '_rewardLegoId',
        type: 'uint256',
      },
      {
        name: '_rewardToken',
        type: 'address',
      },
      {
        name: '_rewardAmount',
        type: 'uint256',
      },
      {
        name: '_rewardProofs',
        type: 'bytes32[]',
      },
      {
        name: '_swapInstructions',
        type: 'tuple[]',
        components: [
          {
            name: 'legoId',
            type: 'uint256',
          },
          {
            name: 'amountIn',
            type: 'uint256',
          },
          {
            name: 'minAmountOut',
            type: 'uint256',
          },
          {
            name: 'tokenPath',
            type: 'address[]',
          },
          {
            name: 'poolPath',
            type: 'address[]',
          },
        ],
      },
      {
        name: '_depositTo',
        type: 'tuple[]',
        components: [
          {
            name: 'legoId',
            type: 'uint256',
          },
          {
            name: 'asset',
            type: 'address',
          },
          {
            name: 'amount',
            type: 'uint256',
          },
          {
            name: 'vaultAddr',
            type: 'address',
          },
        ],
      },
    ],
    outputs: [
      {
        name: '',
        type: 'bytes32',
      },
      {
        name: '',
        type: 'uint256',
      },
      {
        name: '',
        type: 'uint256',
      },
    ],
  },
  {
    stateMutability: 'view',
    type: 'function',
    name: 'getClaimIncentivesAndSwapHash',
    inputs: [
      {
        name: '_agentSender',
        type: 'address',
      },
      {
        name: '_userWallet',
        type: 'address',
      },
      {
        name: '_rewardLegoId',
        type: 'uint256',
      },
      {
        name: '_rewardToken',
        type: 'address',
      },
      {
        name: '_rewardAmount',
        type: 'uint256',
      },
      {
        name: '_rewardProofs',
        type: 'bytes32[]',
      },
      {
        name: '_swapInstructions',
        type: 'tuple[]',
        components: [
          {
            name: 'legoId',
            type: 'uint256',
          },
          {
            name: 'amountIn',
            type: 'uint256',
          },
          {
            name: 'minAmountOut',
            type: 'uint256',
          },
          {
            name: 'tokenPath',
            type: 'address[]',
          },
          {
            name: 'poolPath',
            type: 'address[]',
          },
        ],
      },
      {
        name: '_depositTo',
        type: 'tuple[]',
        components: [
          {
            name: 'legoId',
            type: 'uint256',
          },
          {
            name: 'asset',
            type: 'address',
          },
          {
            name: 'amount',
            type: 'uint256',
          },
          {
            name: 'vaultAddr',
            type: 'address',
          },
        ],
      },
      {
        name: '_debtLegoId',
        type: 'uint256',
      },
    ],
    outputs: [
      {
        name: '',
        type: 'bytes32',
      },
      {
        name: '',
        type: 'uint256',
      },
      {
        name: '',
        type: 'uint256',
      },
    ],
  },
  {
    stateMutability: 'view',
    type: 'function',
    name: 'getClaimIncentivesAndSwapHash',
    inputs: [
      {
        name: '_agentSender',
        type: 'address',
      },
      {
        name: '_userWallet',
        type: 'address',
      },
      {
        name: '_rewardLegoId',
        type: 'uint256',
      },
      {
        name: '_rewardToken',
        type: 'address',
      },
      {
        name: '_rewardAmount',
        type: 'uint256',
      },
      {
        name: '_rewardProofs',
        type: 'bytes32[]',
      },
      {
        name: '_swapInstructions',
        type: 'tuple[]',
        components: [
          {
            name: 'legoId',
            type: 'uint256',
          },
          {
            name: 'amountIn',
            type: 'uint256',
          },
          {
            name: 'minAmountOut',
            type: 'uint256',
          },
          {
            name: 'tokenPath',
            type: 'address[]',
          },
          {
            name: 'poolPath',
            type: 'address[]',
          },
        ],
      },
      {
        name: '_depositTo',
        type: 'tuple[]',
        components: [
          {
            name: 'legoId',
            type: 'uint256',
          },
          {
            name: 'asset',
            type: 'address',
          },
          {
            name: 'amount',
            type: 'uint256',
          },
          {
            name: 'vaultAddr',
            type: 'address',
          },
        ],
      },
      {
        name: '_debtLegoId',
        type: 'uint256',
      },
      {
        name: '_addCollateralAssets',
        type: 'tuple[]',
        components: [
          {
            name: 'vaultId',
            type: 'uint256',
          },
          {
            name: 'asset',
            type: 'address',
          },
          {
            name: 'amount',
            type: 'uint256',
          },
        ],
      },
    ],
    outputs: [
      {
        name: '',
        type: 'bytes32',
      },
      {
        name: '',
        type: 'uint256',
      },
      {
        name: '',
        type: 'uint256',
      },
    ],
  },
  {
    stateMutability: 'view',
    type: 'function',
    name: 'getClaimIncentivesAndSwapHash',
    inputs: [
      {
        name: '_agentSender',
        type: 'address',
      },
      {
        name: '_userWallet',
        type: 'address',
      },
      {
        name: '_rewardLegoId',
        type: 'uint256',
      },
      {
        name: '_rewardToken',
        type: 'address',
      },
      {
        name: '_rewardAmount',
        type: 'uint256',
      },
      {
        name: '_rewardProofs',
        type: 'bytes32[]',
      },
      {
        name: '_swapInstructions',
        type: 'tuple[]',
        components: [
          {
            name: 'legoId',
            type: 'uint256',
          },
          {
            name: 'amountIn',
            type: 'uint256',
          },
          {
            name: 'minAmountOut',
            type: 'uint256',
          },
          {
            name: 'tokenPath',
            type: 'address[]',
          },
          {
            name: 'poolPath',
            type: 'address[]',
          },
        ],
      },
      {
        name: '_depositTo',
        type: 'tuple[]',
        components: [
          {
            name: 'legoId',
            type: 'uint256',
          },
          {
            name: 'asset',
            type: 'address',
          },
          {
            name: 'amount',
            type: 'uint256',
          },
          {
            name: 'vaultAddr',
            type: 'address',
          },
        ],
      },
      {
        name: '_debtLegoId',
        type: 'uint256',
      },
      {
        name: '_addCollateralAssets',
        type: 'tuple[]',
        components: [
          {
            name: 'vaultId',
            type: 'uint256',
          },
          {
            name: 'asset',
            type: 'address',
          },
          {
            name: 'amount',
            type: 'uint256',
          },
        ],
      },
      {
        name: '_nonce',
        type: 'uint256',
      },
    ],
    outputs: [
      {
        name: '',
        type: 'bytes32',
      },
      {
        name: '',
        type: 'uint256',
      },
      {
        name: '',
        type: 'uint256',
      },
    ],
  },
  {
    stateMutability: 'view',
    type: 'function',
    name: 'getClaimIncentivesAndSwapHash',
    inputs: [
      {
        name: '_agentSender',
        type: 'address',
      },
      {
        name: '_userWallet',
        type: 'address',
      },
      {
        name: '_rewardLegoId',
        type: 'uint256',
      },
      {
        name: '_rewardToken',
        type: 'address',
      },
      {
        name: '_rewardAmount',
        type: 'uint256',
      },
      {
        name: '_rewardProofs',
        type: 'bytes32[]',
      },
      {
        name: '_swapInstructions',
        type: 'tuple[]',
        components: [
          {
            name: 'legoId',
            type: 'uint256',
          },
          {
            name: 'amountIn',
            type: 'uint256',
          },
          {
            name: 'minAmountOut',
            type: 'uint256',
          },
          {
            name: 'tokenPath',
            type: 'address[]',
          },
          {
            name: 'poolPath',
            type: 'address[]',
          },
        ],
      },
      {
        name: '_depositTo',
        type: 'tuple[]',
        components: [
          {
            name: 'legoId',
            type: 'uint256',
          },
          {
            name: 'asset',
            type: 'address',
          },
          {
            name: 'amount',
            type: 'uint256',
          },
          {
            name: 'vaultAddr',
            type: 'address',
          },
        ],
      },
      {
        name: '_debtLegoId',
        type: 'uint256',
      },
      {
        name: '_addCollateralAssets',
        type: 'tuple[]',
        components: [
          {
            name: 'vaultId',
            type: 'uint256',
          },
          {
            name: 'asset',
            type: 'address',
          },
          {
            name: 'amount',
            type: 'uint256',
          },
        ],
      },
      {
        name: '_nonce',
        type: 'uint256',
      },
      {
        name: '_expiration',
        type: 'uint256',
      },
    ],
    outputs: [
      {
        name: '',
        type: 'bytes32',
      },
      {
        name: '',
        type: 'uint256',
      },
      {
        name: '',
        type: 'uint256',
      },
    ],
  },
] as const

export const deployAddress: Address | undefined = '0xB9d44E8b964466A2bB1BE747F2e92CD03c4b6D9a'

export type Contract = {
  calls: {
    getAddCollateralAndBorrowHash: (
      agentSender: `0x${string}`,
      userWallet: `0x${string}`,
      debtLegoId: bigint,
      addCollateralAssets?: { vaultId: bigint; asset: `0x${string}`; amount: bigint }[],
      greenBorrowAmount?: bigint,
      wantsSavingsGreen?: boolean,
      shouldEnterStabPool?: boolean,
      swapInstructions?: {
        legoId: bigint
        amountIn: bigint
        minAmountOut: bigint
        tokenPath: `0x${string}`[]
        poolPath: `0x${string}`[]
      }[],
      yieldPosition?: { legoId: bigint; asset: `0x${string}`; amount: bigint; vaultAddr: `0x${string}` },
      nonce?: bigint,
      expiration?: bigint,
    ) => Promise<[`0x${string}`, bigint, bigint]>
    getRepayAndWithdrawHash: (
      agentSender: `0x${string}`,
      userWallet: `0x${string}`,
      debtLegoId: bigint,
      deleverageAssets?: { vaultId: bigint; asset: `0x${string}`; targetRepayAmount: bigint }[],
      yieldPosition?: { legoId: bigint; vaultToken: `0x${string}`; vaultTokenAmount: bigint },
      swapInstructions?: {
        legoId: bigint
        amountIn: bigint
        minAmountOut: bigint
        tokenPath: `0x${string}`[]
        poolPath: `0x${string}`[]
      }[],
      repayAsset?: `0x${string}`,
      repayAmount?: bigint,
      removeCollateralAssets?: { vaultId: bigint; asset: `0x${string}`; amount: bigint }[],
      nonce?: bigint,
      expiration?: bigint,
    ) => Promise<[`0x${string}`, bigint, bigint]>
    getRebalanceYieldPositionsWithSwapHash: (
      agentSender: `0x${string}`,
      userWallet: `0x${string}`,
      withdrawFrom?: { legoId: bigint; vaultToken: `0x${string}`; vaultTokenAmount: bigint }[],
      swapInstructions?: {
        legoId: bigint
        amountIn: bigint
        minAmountOut: bigint
        tokenPath: `0x${string}`[]
        poolPath: `0x${string}`[]
      }[],
      depositTo?: { legoId: bigint; asset: `0x${string}`; amount: bigint; vaultAddr: `0x${string}` }[],
      transferTo?: { asset: `0x${string}`; amount: bigint; recipient: `0x${string}` }[],
      nonce?: bigint,
      expiration?: bigint,
    ) => Promise<[`0x${string}`, bigint, bigint]>
    getClaimIncentivesAndSwapHash: (
      agentSender: `0x${string}`,
      userWallet: `0x${string}`,
      rewardLegoId?: bigint,
      rewardToken?: `0x${string}`,
      rewardAmount?: bigint,
      rewardProofs?: `0x${string}`[],
      swapInstructions?: {
        legoId: bigint
        amountIn: bigint
        minAmountOut: bigint
        tokenPath: `0x${string}`[]
        poolPath: `0x${string}`[]
      }[],
      depositTo?: { legoId: bigint; asset: `0x${string}`; amount: bigint; vaultAddr: `0x${string}` }[],
      debtLegoId?: bigint,
      addCollateralAssets?: { vaultId: bigint; asset: `0x${string}`; amount: bigint }[],
      nonce?: bigint,
      expiration?: bigint,
    ) => Promise<[`0x${string}`, bigint, bigint]>
  }
  mutations: {}
  events: {}
}

export type Calls = keyof Contract['calls']
export type Request<M extends Calls> = {
  contractName: 'AgentSenderSpecialSigHelper'
  method: M
  args: ExtractArgs<Contract['calls'][M]>
  address: Address | undefined
  deployAddress: Address | undefined
  defaultValue: Awaited<ReturnType<Contract['calls'][M]>> | undefined
  getAbi: () => typeof abi
  with: (options: { contractAddress?: Address; defaultValue?: Awaited<ReturnType<Contract['calls'][M]>> }) => Request<M>
  defaultTo: (defaultValue: Awaited<ReturnType<Contract['calls'][M]>>) => Request<M>
  at: (address: Address) => Request<M>
}
export type CallReturn<M extends Calls> = NonNullable<Request<M>['defaultValue']>

function getRequest<M extends Calls>(
  method: M,
  args: ExtractArgs<Contract['calls'][M]>,
  contractAddressOrOptions?:
    | Address
    | {
        contractAddress?: Address
        defaultValue?: Awaited<ReturnType<Contract['calls'][M]>>
      },
): Request<M> {
  const address =
    typeof contractAddressOrOptions === 'string' ? contractAddressOrOptions : contractAddressOrOptions?.contractAddress
  const defaultValue = typeof contractAddressOrOptions === 'string' ? undefined : contractAddressOrOptions?.defaultValue

  const call = {
    contractName: 'AgentSenderSpecialSigHelper' as const,
    method,
    args,
    address,
    deployAddress,
    defaultValue,
    getAbi: () => abi,
    with: (options: { contractAddress?: Address; defaultValue?: Awaited<ReturnType<Contract['calls'][M]>> }) => {
      call.address = options.contractAddress
      call.defaultValue = options.defaultValue
      return call as Request<M>
    },
    defaultTo: (defaultValue: Awaited<ReturnType<Contract['calls'][M]>>) => {
      call.defaultValue = defaultValue
      return call as Request<M>
    },
    at: (address: Address) => {
      call.address = address
      return call as Request<M>
    },
  } as Request<M>

  return call
}

type CallType = {
  [K in Calls]: (...args: ExtractArgs<Contract['calls'][K]>) => ReturnType<typeof getRequest<K>>
}

export const call: CallType = {
  getAddCollateralAndBorrowHash: (...args: ExtractArgs<Contract['calls']['getAddCollateralAndBorrowHash']>) =>
    getRequest('getAddCollateralAndBorrowHash', args),
  getRepayAndWithdrawHash: (...args: ExtractArgs<Contract['calls']['getRepayAndWithdrawHash']>) =>
    getRequest('getRepayAndWithdrawHash', args),
  getRebalanceYieldPositionsWithSwapHash: (
    ...args: ExtractArgs<Contract['calls']['getRebalanceYieldPositionsWithSwapHash']>
  ) => getRequest('getRebalanceYieldPositionsWithSwapHash', args),
  getClaimIncentivesAndSwapHash: (...args: ExtractArgs<Contract['calls']['getClaimIncentivesAndSwapHash']>) =>
    getRequest('getClaimIncentivesAndSwapHash', args),
}

export type SDK = {
  deployAddress: Address | undefined
  abi: typeof abi
  getAddCollateralAndBorrowHash: (
    ...args: ExtractArgs<Contract['calls']['getAddCollateralAndBorrowHash']>
  ) => Promise<CallReturn<'getAddCollateralAndBorrowHash'>>
  getRepayAndWithdrawHash: (
    ...args: ExtractArgs<Contract['calls']['getRepayAndWithdrawHash']>
  ) => Promise<CallReturn<'getRepayAndWithdrawHash'>>
  getRebalanceYieldPositionsWithSwapHash: (
    ...args: ExtractArgs<Contract['calls']['getRebalanceYieldPositionsWithSwapHash']>
  ) => Promise<CallReturn<'getRebalanceYieldPositionsWithSwapHash'>>
  getClaimIncentivesAndSwapHash: (
    ...args: ExtractArgs<Contract['calls']['getClaimIncentivesAndSwapHash']>
  ) => Promise<CallReturn<'getClaimIncentivesAndSwapHash'>>
}

export function toSdk(
  publicClient?: PublicClient,
  walletClient?: WalletClient,
  addressResolver?: AddressResolverFunction,
): SDK {
  return {
    deployAddress,
    abi,

    // Queries
    getAddCollateralAndBorrowHash: (...args: ExtractArgs<Contract['calls']['getAddCollateralAndBorrowHash']>) =>
      singleQuery(publicClient!, call.getAddCollateralAndBorrowHash(...args), {}, addressResolver) as Promise<
        CallReturn<'getAddCollateralAndBorrowHash'>
      >,
    getRepayAndWithdrawHash: (...args: ExtractArgs<Contract['calls']['getRepayAndWithdrawHash']>) =>
      singleQuery(publicClient!, call.getRepayAndWithdrawHash(...args), {}, addressResolver) as Promise<
        CallReturn<'getRepayAndWithdrawHash'>
      >,
    getRebalanceYieldPositionsWithSwapHash: (
      ...args: ExtractArgs<Contract['calls']['getRebalanceYieldPositionsWithSwapHash']>
    ) =>
      singleQuery(publicClient!, call.getRebalanceYieldPositionsWithSwapHash(...args), {}, addressResolver) as Promise<
        CallReturn<'getRebalanceYieldPositionsWithSwapHash'>
      >,
    getClaimIncentivesAndSwapHash: (...args: ExtractArgs<Contract['calls']['getClaimIncentivesAndSwapHash']>) =>
      singleQuery(publicClient!, call.getClaimIncentivesAndSwapHash(...args), {}, addressResolver) as Promise<
        CallReturn<'getClaimIncentivesAndSwapHash'>
      >,

    // Mutations
  }
}
