/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
/* @ts-nocheck */

import { singleQuery, mutate, AddressResolverFunction } from '@dappql/async'
import {
  encodeEventTopics,
  parseEventLogs,
  ParseEventLogsReturnType,
  Log,
  RpcLog,
  PublicClient,
  WalletClient,
} from 'viem'

type ExtractArgs<T> = T extends (...args: infer P) => any ? P : never
type Address = `0x${string}`

export const abi = [
  {
    name: 'HqConfigChangeInitiated',
    inputs: [
      {
        name: 'regId',
        type: 'uint256',
        indexed: false,
      },
      {
        name: 'description',
        type: 'string',
        indexed: false,
      },
      {
        name: 'canMintUndy',
        type: 'bool',
        indexed: false,
      },
      {
        name: 'canSetTokenBlacklist',
        type: 'bool',
        indexed: false,
      },
      {
        name: 'confirmBlock',
        type: 'uint256',
        indexed: false,
      },
    ],
    anonymous: false,
    type: 'event',
  },
  {
    name: 'HqConfigChangeConfirmed',
    inputs: [
      {
        name: 'regId',
        type: 'uint256',
        indexed: false,
      },
      {
        name: 'description',
        type: 'string',
        indexed: false,
      },
      {
        name: 'canMintUndy',
        type: 'bool',
        indexed: false,
      },
      {
        name: 'canSetTokenBlacklist',
        type: 'bool',
        indexed: false,
      },
      {
        name: 'initiatedBlock',
        type: 'uint256',
        indexed: false,
      },
      {
        name: 'confirmBlock',
        type: 'uint256',
        indexed: false,
      },
    ],
    anonymous: false,
    type: 'event',
  },
  {
    name: 'HqConfigChangeCancelled',
    inputs: [
      {
        name: 'regId',
        type: 'uint256',
        indexed: false,
      },
      {
        name: 'description',
        type: 'string',
        indexed: false,
      },
      {
        name: 'canMintUndy',
        type: 'bool',
        indexed: false,
      },
      {
        name: 'canSetTokenBlacklist',
        type: 'bool',
        indexed: false,
      },
      {
        name: 'initiatedBlock',
        type: 'uint256',
        indexed: false,
      },
      {
        name: 'confirmBlock',
        type: 'uint256',
        indexed: false,
      },
    ],
    anonymous: false,
    type: 'event',
  },
  {
    name: 'UndyHqFundsRecovered',
    inputs: [
      {
        name: 'asset',
        type: 'address',
        indexed: true,
      },
      {
        name: 'recipient',
        type: 'address',
        indexed: true,
      },
      {
        name: 'balance',
        type: 'uint256',
        indexed: false,
      },
    ],
    anonymous: false,
    type: 'event',
  },
  {
    name: 'UndyTokenSet',
    inputs: [
      {
        name: 'token',
        type: 'address',
        indexed: true,
      },
    ],
    anonymous: false,
    type: 'event',
  },
  {
    name: 'MintingEnabled',
    inputs: [
      {
        name: 'isEnabled',
        type: 'bool',
        indexed: false,
      },
    ],
    anonymous: false,
    type: 'event',
  },
  {
    name: 'GovChangeTimeLockModified',
    inputs: [
      {
        name: 'prevTimeLock',
        type: 'uint256',
        indexed: false,
      },
      {
        name: 'newTimeLock',
        type: 'uint256',
        indexed: false,
      },
    ],
    anonymous: false,
    type: 'event',
  },
  {
    name: 'RegistryTimeLockModified',
    inputs: [
      {
        name: 'newTimeLock',
        type: 'uint256',
        indexed: false,
      },
      {
        name: 'prevTimeLock',
        type: 'uint256',
        indexed: false,
      },
      {
        name: 'registry',
        type: 'string',
        indexed: false,
      },
    ],
    anonymous: false,
    type: 'event',
  },
  {
    name: 'GovChangeStarted',
    inputs: [
      {
        name: 'prevGov',
        type: 'address',
        indexed: true,
      },
      {
        name: 'newGov',
        type: 'address',
        indexed: true,
      },
      {
        name: 'confirmBlock',
        type: 'uint256',
        indexed: false,
      },
    ],
    anonymous: false,
    type: 'event',
  },
  {
    name: 'GovChangeConfirmed',
    inputs: [
      {
        name: 'prevGov',
        type: 'address',
        indexed: true,
      },
      {
        name: 'newGov',
        type: 'address',
        indexed: true,
      },
      {
        name: 'initiatedBlock',
        type: 'uint256',
        indexed: false,
      },
      {
        name: 'confirmBlock',
        type: 'uint256',
        indexed: false,
      },
    ],
    anonymous: false,
    type: 'event',
  },
  {
    name: 'GovChangeCancelled',
    inputs: [
      {
        name: 'cancelledGov',
        type: 'address',
        indexed: true,
      },
      {
        name: 'initiatedBlock',
        type: 'uint256',
        indexed: false,
      },
      {
        name: 'confirmBlock',
        type: 'uint256',
        indexed: false,
      },
    ],
    anonymous: false,
    type: 'event',
  },
  {
    name: 'GovRelinquished',
    inputs: [
      {
        name: 'prevGov',
        type: 'address',
        indexed: true,
      },
    ],
    anonymous: false,
    type: 'event',
  },
  {
    name: 'UndyHqSetupFinished',
    inputs: [
      {
        name: 'prevGov',
        type: 'address',
        indexed: true,
      },
      {
        name: 'newGov',
        type: 'address',
        indexed: true,
      },
      {
        name: 'timeLock',
        type: 'uint256',
        indexed: false,
      },
    ],
    anonymous: false,
    type: 'event',
  },
  {
    name: 'NewAddressPending',
    inputs: [
      {
        name: 'addr',
        type: 'address',
        indexed: true,
      },
      {
        name: 'description',
        type: 'string',
        indexed: false,
      },
      {
        name: 'confirmBlock',
        type: 'uint256',
        indexed: false,
      },
      {
        name: 'registry',
        type: 'string',
        indexed: false,
      },
    ],
    anonymous: false,
    type: 'event',
  },
  {
    name: 'NewAddressConfirmed',
    inputs: [
      {
        name: 'addr',
        type: 'address',
        indexed: true,
      },
      {
        name: 'regId',
        type: 'uint256',
        indexed: false,
      },
      {
        name: 'description',
        type: 'string',
        indexed: false,
      },
      {
        name: 'registry',
        type: 'string',
        indexed: false,
      },
    ],
    anonymous: false,
    type: 'event',
  },
  {
    name: 'NewAddressCancelled',
    inputs: [
      {
        name: 'description',
        type: 'string',
        indexed: false,
      },
      {
        name: 'addr',
        type: 'address',
        indexed: true,
      },
      {
        name: 'initiatedBlock',
        type: 'uint256',
        indexed: false,
      },
      {
        name: 'confirmBlock',
        type: 'uint256',
        indexed: false,
      },
      {
        name: 'registry',
        type: 'string',
        indexed: false,
      },
    ],
    anonymous: false,
    type: 'event',
  },
  {
    name: 'AddressUpdatePending',
    inputs: [
      {
        name: 'regId',
        type: 'uint256',
        indexed: false,
      },
      {
        name: 'description',
        type: 'string',
        indexed: false,
      },
      {
        name: 'newAddr',
        type: 'address',
        indexed: true,
      },
      {
        name: 'prevAddr',
        type: 'address',
        indexed: true,
      },
      {
        name: 'version',
        type: 'uint256',
        indexed: false,
      },
      {
        name: 'confirmBlock',
        type: 'uint256',
        indexed: false,
      },
      {
        name: 'registry',
        type: 'string',
        indexed: false,
      },
    ],
    anonymous: false,
    type: 'event',
  },
  {
    name: 'AddressUpdateConfirmed',
    inputs: [
      {
        name: 'regId',
        type: 'uint256',
        indexed: false,
      },
      {
        name: 'description',
        type: 'string',
        indexed: false,
      },
      {
        name: 'newAddr',
        type: 'address',
        indexed: true,
      },
      {
        name: 'prevAddr',
        type: 'address',
        indexed: true,
      },
      {
        name: 'version',
        type: 'uint256',
        indexed: false,
      },
      {
        name: 'registry',
        type: 'string',
        indexed: false,
      },
    ],
    anonymous: false,
    type: 'event',
  },
  {
    name: 'AddressUpdateCancelled',
    inputs: [
      {
        name: 'regId',
        type: 'uint256',
        indexed: false,
      },
      {
        name: 'description',
        type: 'string',
        indexed: false,
      },
      {
        name: 'newAddr',
        type: 'address',
        indexed: true,
      },
      {
        name: 'prevAddr',
        type: 'address',
        indexed: true,
      },
      {
        name: 'initiatedBlock',
        type: 'uint256',
        indexed: false,
      },
      {
        name: 'confirmBlock',
        type: 'uint256',
        indexed: false,
      },
      {
        name: 'registry',
        type: 'string',
        indexed: false,
      },
    ],
    anonymous: false,
    type: 'event',
  },
  {
    name: 'AddressDisablePending',
    inputs: [
      {
        name: 'regId',
        type: 'uint256',
        indexed: false,
      },
      {
        name: 'description',
        type: 'string',
        indexed: false,
      },
      {
        name: 'addr',
        type: 'address',
        indexed: true,
      },
      {
        name: 'version',
        type: 'uint256',
        indexed: false,
      },
      {
        name: 'confirmBlock',
        type: 'uint256',
        indexed: false,
      },
      {
        name: 'registry',
        type: 'string',
        indexed: false,
      },
    ],
    anonymous: false,
    type: 'event',
  },
  {
    name: 'AddressDisableConfirmed',
    inputs: [
      {
        name: 'regId',
        type: 'uint256',
        indexed: false,
      },
      {
        name: 'description',
        type: 'string',
        indexed: false,
      },
      {
        name: 'addr',
        type: 'address',
        indexed: true,
      },
      {
        name: 'version',
        type: 'uint256',
        indexed: false,
      },
      {
        name: 'registry',
        type: 'string',
        indexed: false,
      },
    ],
    anonymous: false,
    type: 'event',
  },
  {
    name: 'AddressDisableCancelled',
    inputs: [
      {
        name: 'regId',
        type: 'uint256',
        indexed: false,
      },
      {
        name: 'description',
        type: 'string',
        indexed: false,
      },
      {
        name: 'addr',
        type: 'address',
        indexed: true,
      },
      {
        name: 'initiatedBlock',
        type: 'uint256',
        indexed: false,
      },
      {
        name: 'confirmBlock',
        type: 'uint256',
        indexed: false,
      },
      {
        name: 'registry',
        type: 'string',
        indexed: false,
      },
    ],
    anonymous: false,
    type: 'event',
  },
  {
    stateMutability: 'view',
    type: 'function',
    name: 'getUndyHqFromGov',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'address',
      },
    ],
  },
  {
    stateMutability: 'view',
    type: 'function',
    name: 'canGovern',
    inputs: [
      {
        name: '_addr',
        type: 'address',
      },
    ],
    outputs: [
      {
        name: '',
        type: 'bool',
      },
    ],
  },
  {
    stateMutability: 'view',
    type: 'function',
    name: 'getGovernors',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'address[]',
      },
    ],
  },
  {
    stateMutability: 'view',
    type: 'function',
    name: 'hasPendingGovChange',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'bool',
      },
    ],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    name: 'startGovernanceChange',
    inputs: [
      {
        name: '_newGov',
        type: 'address',
      },
    ],
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    name: 'confirmGovernanceChange',
    inputs: [],
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    name: 'cancelGovernanceChange',
    inputs: [],
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    name: 'relinquishGov',
    inputs: [],
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    name: 'setGovTimeLock',
    inputs: [
      {
        name: '_numBlocks',
        type: 'uint256',
      },
    ],
    outputs: [
      {
        name: '',
        type: 'bool',
      },
    ],
  },
  {
    stateMutability: 'view',
    type: 'function',
    name: 'isValidGovTimeLock',
    inputs: [
      {
        name: '_newTimeLock',
        type: 'uint256',
      },
    ],
    outputs: [
      {
        name: '',
        type: 'bool',
      },
    ],
  },
  {
    stateMutability: 'view',
    type: 'function',
    name: 'minGovChangeTimeLock',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'uint256',
      },
    ],
  },
  {
    stateMutability: 'view',
    type: 'function',
    name: 'maxGovChangeTimeLock',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'uint256',
      },
    ],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    name: 'finishUndyHqSetup',
    inputs: [
      {
        name: '_newGov',
        type: 'address',
      },
    ],
    outputs: [
      {
        name: '',
        type: 'bool',
      },
    ],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    name: 'finishUndyHqSetup',
    inputs: [
      {
        name: '_newGov',
        type: 'address',
      },
      {
        name: '_timeLock',
        type: 'uint256',
      },
    ],
    outputs: [
      {
        name: '',
        type: 'bool',
      },
    ],
  },
  {
    stateMutability: 'view',
    type: 'function',
    name: 'governance',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'address',
      },
    ],
  },
  {
    stateMutability: 'view',
    type: 'function',
    name: 'pendingGov',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'tuple',
        components: [
          {
            name: 'newGov',
            type: 'address',
          },
          {
            name: 'initiatedBlock',
            type: 'uint256',
          },
          {
            name: 'confirmBlock',
            type: 'uint256',
          },
        ],
      },
    ],
  },
  {
    stateMutability: 'view',
    type: 'function',
    name: 'numGovChanges',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'uint256',
      },
    ],
  },
  {
    stateMutability: 'view',
    type: 'function',
    name: 'govChangeTimeLock',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'uint256',
      },
    ],
  },
  {
    stateMutability: 'view',
    type: 'function',
    name: 'getRegistryDescription',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'string',
      },
    ],
  },
  {
    stateMutability: 'view',
    type: 'function',
    name: 'isValidNewAddress',
    inputs: [
      {
        name: '_addr',
        type: 'address',
      },
    ],
    outputs: [
      {
        name: '',
        type: 'bool',
      },
    ],
  },
  {
    stateMutability: 'view',
    type: 'function',
    name: 'isValidAddressUpdate',
    inputs: [
      {
        name: '_regId',
        type: 'uint256',
      },
      {
        name: '_newAddr',
        type: 'address',
      },
    ],
    outputs: [
      {
        name: '',
        type: 'bool',
      },
    ],
  },
  {
    stateMutability: 'view',
    type: 'function',
    name: 'isValidAddressDisable',
    inputs: [
      {
        name: '_regId',
        type: 'uint256',
      },
    ],
    outputs: [
      {
        name: '',
        type: 'bool',
      },
    ],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    name: 'setRegistryTimeLock',
    inputs: [
      {
        name: '_numBlocks',
        type: 'uint256',
      },
    ],
    outputs: [
      {
        name: '',
        type: 'bool',
      },
    ],
  },
  {
    stateMutability: 'view',
    type: 'function',
    name: 'isValidRegistryTimeLock',
    inputs: [
      {
        name: '_numBlocks',
        type: 'uint256',
      },
    ],
    outputs: [
      {
        name: '',
        type: 'bool',
      },
    ],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    name: 'setRegistryTimeLockAfterSetup',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'bool',
      },
    ],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    name: 'setRegistryTimeLockAfterSetup',
    inputs: [
      {
        name: '_numBlocks',
        type: 'uint256',
      },
    ],
    outputs: [
      {
        name: '',
        type: 'bool',
      },
    ],
  },
  {
    stateMutability: 'view',
    type: 'function',
    name: 'minRegistryTimeLock',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'uint256',
      },
    ],
  },
  {
    stateMutability: 'view',
    type: 'function',
    name: 'maxRegistryTimeLock',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'uint256',
      },
    ],
  },
  {
    stateMutability: 'view',
    type: 'function',
    name: 'isValidAddr',
    inputs: [
      {
        name: '_addr',
        type: 'address',
      },
    ],
    outputs: [
      {
        name: '',
        type: 'bool',
      },
    ],
  },
  {
    stateMutability: 'view',
    type: 'function',
    name: 'isValidRegId',
    inputs: [
      {
        name: '_regId',
        type: 'uint256',
      },
    ],
    outputs: [
      {
        name: '',
        type: 'bool',
      },
    ],
  },
  {
    stateMutability: 'view',
    type: 'function',
    name: 'getRegId',
    inputs: [
      {
        name: '_addr',
        type: 'address',
      },
    ],
    outputs: [
      {
        name: '',
        type: 'uint256',
      },
    ],
  },
  {
    stateMutability: 'view',
    type: 'function',
    name: 'getAddr',
    inputs: [
      {
        name: '_regId',
        type: 'uint256',
      },
    ],
    outputs: [
      {
        name: '',
        type: 'address',
      },
    ],
  },
  {
    stateMutability: 'view',
    type: 'function',
    name: 'getAddrInfo',
    inputs: [
      {
        name: '_regId',
        type: 'uint256',
      },
    ],
    outputs: [
      {
        name: '',
        type: 'tuple',
        components: [
          {
            name: 'addr',
            type: 'address',
          },
          {
            name: 'version',
            type: 'uint256',
          },
          {
            name: 'lastModified',
            type: 'uint256',
          },
          {
            name: 'description',
            type: 'string',
          },
        ],
      },
    ],
  },
  {
    stateMutability: 'view',
    type: 'function',
    name: 'getAddrDescription',
    inputs: [
      {
        name: '_regId',
        type: 'uint256',
      },
    ],
    outputs: [
      {
        name: '',
        type: 'string',
      },
    ],
  },
  {
    stateMutability: 'view',
    type: 'function',
    name: 'getNumAddrs',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'uint256',
      },
    ],
  },
  {
    stateMutability: 'view',
    type: 'function',
    name: 'getLastAddr',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'address',
      },
    ],
  },
  {
    stateMutability: 'view',
    type: 'function',
    name: 'getLastRegId',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'uint256',
      },
    ],
  },
  {
    stateMutability: 'view',
    type: 'function',
    name: 'registryChangeTimeLock',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'uint256',
      },
    ],
  },
  {
    stateMutability: 'view',
    type: 'function',
    name: 'addrInfo',
    inputs: [
      {
        name: 'arg0',
        type: 'uint256',
      },
    ],
    outputs: [
      {
        name: '',
        type: 'tuple',
        components: [
          {
            name: 'addr',
            type: 'address',
          },
          {
            name: 'version',
            type: 'uint256',
          },
          {
            name: 'lastModified',
            type: 'uint256',
          },
          {
            name: 'description',
            type: 'string',
          },
        ],
      },
    ],
  },
  {
    stateMutability: 'view',
    type: 'function',
    name: 'addrToRegId',
    inputs: [
      {
        name: 'arg0',
        type: 'address',
      },
    ],
    outputs: [
      {
        name: '',
        type: 'uint256',
      },
    ],
  },
  {
    stateMutability: 'view',
    type: 'function',
    name: 'numAddrs',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'uint256',
      },
    ],
  },
  {
    stateMutability: 'view',
    type: 'function',
    name: 'pendingNewAddr',
    inputs: [
      {
        name: 'arg0',
        type: 'address',
      },
    ],
    outputs: [
      {
        name: '',
        type: 'tuple',
        components: [
          {
            name: 'description',
            type: 'string',
          },
          {
            name: 'initiatedBlock',
            type: 'uint256',
          },
          {
            name: 'confirmBlock',
            type: 'uint256',
          },
        ],
      },
    ],
  },
  {
    stateMutability: 'view',
    type: 'function',
    name: 'pendingAddrUpdate',
    inputs: [
      {
        name: 'arg0',
        type: 'uint256',
      },
    ],
    outputs: [
      {
        name: '',
        type: 'tuple',
        components: [
          {
            name: 'newAddr',
            type: 'address',
          },
          {
            name: 'initiatedBlock',
            type: 'uint256',
          },
          {
            name: 'confirmBlock',
            type: 'uint256',
          },
        ],
      },
    ],
  },
  {
    stateMutability: 'view',
    type: 'function',
    name: 'pendingAddrDisable',
    inputs: [
      {
        name: 'arg0',
        type: 'uint256',
      },
    ],
    outputs: [
      {
        name: '',
        type: 'tuple',
        components: [
          {
            name: 'initiatedBlock',
            type: 'uint256',
          },
          {
            name: 'confirmBlock',
            type: 'uint256',
          },
        ],
      },
    ],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    name: 'startAddNewAddressToRegistry',
    inputs: [
      {
        name: '_addr',
        type: 'address',
      },
      {
        name: '_description',
        type: 'string',
      },
    ],
    outputs: [
      {
        name: '',
        type: 'bool',
      },
    ],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    name: 'confirmNewAddressToRegistry',
    inputs: [
      {
        name: '_addr',
        type: 'address',
      },
    ],
    outputs: [
      {
        name: '',
        type: 'uint256',
      },
    ],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    name: 'cancelNewAddressToRegistry',
    inputs: [
      {
        name: '_addr',
        type: 'address',
      },
    ],
    outputs: [
      {
        name: '',
        type: 'bool',
      },
    ],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    name: 'startAddressUpdateToRegistry',
    inputs: [
      {
        name: '_regId',
        type: 'uint256',
      },
      {
        name: '_newAddr',
        type: 'address',
      },
    ],
    outputs: [
      {
        name: '',
        type: 'bool',
      },
    ],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    name: 'confirmAddressUpdateToRegistry',
    inputs: [
      {
        name: '_regId',
        type: 'uint256',
      },
    ],
    outputs: [
      {
        name: '',
        type: 'bool',
      },
    ],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    name: 'cancelAddressUpdateToRegistry',
    inputs: [
      {
        name: '_regId',
        type: 'uint256',
      },
    ],
    outputs: [
      {
        name: '',
        type: 'bool',
      },
    ],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    name: 'startAddressDisableInRegistry',
    inputs: [
      {
        name: '_regId',
        type: 'uint256',
      },
    ],
    outputs: [
      {
        name: '',
        type: 'bool',
      },
    ],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    name: 'confirmAddressDisableInRegistry',
    inputs: [
      {
        name: '_regId',
        type: 'uint256',
      },
    ],
    outputs: [
      {
        name: '',
        type: 'bool',
      },
    ],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    name: 'cancelAddressDisableInRegistry',
    inputs: [
      {
        name: '_regId',
        type: 'uint256',
      },
    ],
    outputs: [
      {
        name: '',
        type: 'bool',
      },
    ],
  },
  {
    stateMutability: 'view',
    type: 'function',
    name: 'hasPendingHqConfigChange',
    inputs: [
      {
        name: '_regId',
        type: 'uint256',
      },
    ],
    outputs: [
      {
        name: '',
        type: 'bool',
      },
    ],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    name: 'initiateHqConfigChange',
    inputs: [
      {
        name: '_regId',
        type: 'uint256',
      },
      {
        name: '_canMintUndy',
        type: 'bool',
      },
      {
        name: '_canSetTokenBlacklist',
        type: 'bool',
      },
    ],
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    name: 'confirmHqConfigChange',
    inputs: [
      {
        name: '_regId',
        type: 'uint256',
      },
    ],
    outputs: [
      {
        name: '',
        type: 'bool',
      },
    ],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    name: 'cancelHqConfigChange',
    inputs: [
      {
        name: '_regId',
        type: 'uint256',
      },
    ],
    outputs: [
      {
        name: '',
        type: 'bool',
      },
    ],
  },
  {
    stateMutability: 'view',
    type: 'function',
    name: 'isValidHqConfig',
    inputs: [
      {
        name: '_regId',
        type: 'uint256',
      },
      {
        name: '_canMintUndy',
        type: 'bool',
      },
    ],
    outputs: [
      {
        name: '',
        type: 'bool',
      },
    ],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    name: 'setUndyToken',
    inputs: [
      {
        name: '_token',
        type: 'address',
      },
    ],
    outputs: [],
  },
  {
    stateMutability: 'view',
    type: 'function',
    name: 'canMintUndy',
    inputs: [
      {
        name: '_addr',
        type: 'address',
      },
    ],
    outputs: [
      {
        name: '',
        type: 'bool',
      },
    ],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    name: 'setMintingEnabled',
    inputs: [
      {
        name: '_shouldEnable',
        type: 'bool',
      },
    ],
    outputs: [],
  },
  {
    stateMutability: 'view',
    type: 'function',
    name: 'canSetTokenBlacklist',
    inputs: [
      {
        name: '_addr',
        type: 'address',
      },
    ],
    outputs: [
      {
        name: '',
        type: 'bool',
      },
    ],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    name: 'recoverFunds',
    inputs: [
      {
        name: '_recipient',
        type: 'address',
      },
      {
        name: '_asset',
        type: 'address',
      },
    ],
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    name: 'recoverFundsMany',
    inputs: [
      {
        name: '_recipient',
        type: 'address',
      },
      {
        name: '_assets',
        type: 'address[]',
      },
    ],
    outputs: [],
  },
  {
    stateMutability: 'view',
    type: 'function',
    name: 'undyToken',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'address',
      },
    ],
  },
  {
    stateMutability: 'view',
    type: 'function',
    name: 'mintEnabled',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'bool',
      },
    ],
  },
  {
    stateMutability: 'view',
    type: 'function',
    name: 'hqConfig',
    inputs: [
      {
        name: 'arg0',
        type: 'uint256',
      },
    ],
    outputs: [
      {
        name: '',
        type: 'tuple',
        components: [
          {
            name: 'description',
            type: 'string',
          },
          {
            name: 'canMintUndy',
            type: 'bool',
          },
          {
            name: 'canSetTokenBlacklist',
            type: 'bool',
          },
        ],
      },
    ],
  },
  {
    stateMutability: 'view',
    type: 'function',
    name: 'pendingHqConfig',
    inputs: [
      {
        name: 'arg0',
        type: 'uint256',
      },
    ],
    outputs: [
      {
        name: '',
        type: 'tuple',
        components: [
          {
            name: 'newHqConfig',
            type: 'tuple',
            components: [
              {
                name: 'description',
                type: 'string',
              },
              {
                name: 'canMintUndy',
                type: 'bool',
              },
              {
                name: 'canSetTokenBlacklist',
                type: 'bool',
              },
            ],
          },
          {
            name: 'initiatedBlock',
            type: 'uint256',
          },
          {
            name: 'confirmBlock',
            type: 'uint256',
          },
        ],
      },
    ],
  },
  {
    stateMutability: 'nonpayable',
    type: 'constructor',
    inputs: [
      {
        name: '_initialGov',
        type: 'address',
      },
      {
        name: '_minGovTimeLock',
        type: 'uint256',
      },
      {
        name: '_maxGovTimeLock',
        type: 'uint256',
      },
      {
        name: '_minRegistryTimeLock',
        type: 'uint256',
      },
      {
        name: '_maxRegistryTimeLock',
        type: 'uint256',
      },
    ],
    outputs: [],
  },
] as const

export const deployAddress: Address | undefined = '0x44Cf3c4f000DFD76a35d03298049D37bE688D6F9'

export type Contract = {
  calls: {
    getUndyHqFromGov: () => Promise<`0x${string}`>
    canGovern: (addr: `0x${string}`) => Promise<boolean>
    getGovernors: () => Promise<`0x${string}`[]>
    hasPendingGovChange: () => Promise<boolean>
    isValidGovTimeLock: (newTimeLock: bigint) => Promise<boolean>
    minGovChangeTimeLock: () => Promise<bigint>
    maxGovChangeTimeLock: () => Promise<bigint>
    governance: () => Promise<`0x${string}`>
    pendingGov: () => Promise<{ newGov: `0x${string}`; initiatedBlock: bigint; confirmBlock: bigint }>
    numGovChanges: () => Promise<bigint>
    govChangeTimeLock: () => Promise<bigint>
    getRegistryDescription: () => Promise<string>
    isValidNewAddress: (addr: `0x${string}`) => Promise<boolean>
    isValidAddressUpdate: (regId: bigint, newAddr: `0x${string}`) => Promise<boolean>
    isValidAddressDisable: (regId: bigint) => Promise<boolean>
    isValidRegistryTimeLock: (numBlocks: bigint) => Promise<boolean>
    minRegistryTimeLock: () => Promise<bigint>
    maxRegistryTimeLock: () => Promise<bigint>
    isValidAddr: (addr: `0x${string}`) => Promise<boolean>
    isValidRegId: (regId: bigint) => Promise<boolean>
    getRegId: (addr: `0x${string}`) => Promise<bigint>
    getAddr: (regId: bigint) => Promise<`0x${string}`>
    getAddrInfo: (
      regId: bigint,
    ) => Promise<{ addr: `0x${string}`; version: bigint; lastModified: bigint; description: string }>
    getAddrDescription: (regId: bigint) => Promise<string>
    getNumAddrs: () => Promise<bigint>
    getLastAddr: () => Promise<`0x${string}`>
    getLastRegId: () => Promise<bigint>
    registryChangeTimeLock: () => Promise<bigint>
    addrInfo: (
      arg0: bigint,
    ) => Promise<{ addr: `0x${string}`; version: bigint; lastModified: bigint; description: string }>
    addrToRegId: (arg0: `0x${string}`) => Promise<bigint>
    numAddrs: () => Promise<bigint>
    pendingNewAddr: (
      arg0: `0x${string}`,
    ) => Promise<{ description: string; initiatedBlock: bigint; confirmBlock: bigint }>
    pendingAddrUpdate: (
      arg0: bigint,
    ) => Promise<{ newAddr: `0x${string}`; initiatedBlock: bigint; confirmBlock: bigint }>
    pendingAddrDisable: (arg0: bigint) => Promise<{ initiatedBlock: bigint; confirmBlock: bigint }>
    hasPendingHqConfigChange: (regId: bigint) => Promise<boolean>
    isValidHqConfig: (regId: bigint, canMintUndy: boolean) => Promise<boolean>
    canMintUndy: (addr: `0x${string}`) => Promise<boolean>
    canSetTokenBlacklist: (addr: `0x${string}`) => Promise<boolean>
    undyToken: () => Promise<`0x${string}`>
    mintEnabled: () => Promise<boolean>
    hqConfig: (arg0: bigint) => Promise<{ description: string; canMintUndy: boolean; canSetTokenBlacklist: boolean }>
    pendingHqConfig: (
      arg0: bigint,
    ) => Promise<{
      newHqConfig: { description: string; canMintUndy: boolean; canSetTokenBlacklist: boolean }
      initiatedBlock: bigint
      confirmBlock: bigint
    }>
  }
  mutations: {
    startGovernanceChange: (newGov: `0x${string}`) => Promise<void>
    confirmGovernanceChange: () => Promise<void>
    cancelGovernanceChange: () => Promise<void>
    relinquishGov: () => Promise<void>
    setGovTimeLock: (numBlocks: bigint) => Promise<boolean>
    finishUndyHqSetup: (newGov: `0x${string}`, timeLock?: bigint) => Promise<boolean>
    setRegistryTimeLock: (numBlocks: bigint) => Promise<boolean>
    setRegistryTimeLockAfterSetup: (numBlocks?: bigint) => Promise<boolean>
    startAddNewAddressToRegistry: (addr: `0x${string}`, description: string) => Promise<boolean>
    confirmNewAddressToRegistry: (addr: `0x${string}`) => Promise<bigint>
    cancelNewAddressToRegistry: (addr: `0x${string}`) => Promise<boolean>
    startAddressUpdateToRegistry: (regId: bigint, newAddr: `0x${string}`) => Promise<boolean>
    confirmAddressUpdateToRegistry: (regId: bigint) => Promise<boolean>
    cancelAddressUpdateToRegistry: (regId: bigint) => Promise<boolean>
    startAddressDisableInRegistry: (regId: bigint) => Promise<boolean>
    confirmAddressDisableInRegistry: (regId: bigint) => Promise<boolean>
    cancelAddressDisableInRegistry: (regId: bigint) => Promise<boolean>
    initiateHqConfigChange: (regId: bigint, canMintUndy: boolean, canSetTokenBlacklist: boolean) => Promise<void>
    confirmHqConfigChange: (regId: bigint) => Promise<boolean>
    cancelHqConfigChange: (regId: bigint) => Promise<boolean>
    setUndyToken: (token: `0x${string}`) => Promise<void>
    setMintingEnabled: (shouldEnable: boolean) => Promise<void>
    recoverFunds: (recipient: `0x${string}`, asset: `0x${string}`) => Promise<void>
    recoverFundsMany: (recipient: `0x${string}`, assets: `0x${string}`[]) => Promise<void>
  }
  events: {
    HqConfigChangeInitiated: (
      regId: bigint,
      description: string,
      canMintUndy: boolean,
      canSetTokenBlacklist: boolean,
      confirmBlock: bigint,
    ) => Promise<void>
    HqConfigChangeConfirmed: (
      regId: bigint,
      description: string,
      canMintUndy: boolean,
      canSetTokenBlacklist: boolean,
      initiatedBlock: bigint,
      confirmBlock: bigint,
    ) => Promise<void>
    HqConfigChangeCancelled: (
      regId: bigint,
      description: string,
      canMintUndy: boolean,
      canSetTokenBlacklist: boolean,
      initiatedBlock: bigint,
      confirmBlock: bigint,
    ) => Promise<void>
    UndyHqFundsRecovered: (asset: `0x${string}`, recipient: `0x${string}`, balance: bigint) => Promise<void>
    UndyTokenSet: (token: `0x${string}`) => Promise<void>
    MintingEnabled: (isEnabled: boolean) => Promise<void>
    GovChangeTimeLockModified: (prevTimeLock: bigint, newTimeLock: bigint) => Promise<void>
    RegistryTimeLockModified: (newTimeLock: bigint, prevTimeLock: bigint, registry: string) => Promise<void>
    GovChangeStarted: (prevGov: `0x${string}`, newGov: `0x${string}`, confirmBlock: bigint) => Promise<void>
    GovChangeConfirmed: (
      prevGov: `0x${string}`,
      newGov: `0x${string}`,
      initiatedBlock: bigint,
      confirmBlock: bigint,
    ) => Promise<void>
    GovChangeCancelled: (cancelledGov: `0x${string}`, initiatedBlock: bigint, confirmBlock: bigint) => Promise<void>
    GovRelinquished: (prevGov: `0x${string}`) => Promise<void>
    UndyHqSetupFinished: (prevGov: `0x${string}`, newGov: `0x${string}`, timeLock: bigint) => Promise<void>
    NewAddressPending: (
      addr: `0x${string}`,
      description: string,
      confirmBlock: bigint,
      registry: string,
    ) => Promise<void>
    NewAddressConfirmed: (addr: `0x${string}`, regId: bigint, description: string, registry: string) => Promise<void>
    NewAddressCancelled: (
      description: string,
      addr: `0x${string}`,
      initiatedBlock: bigint,
      confirmBlock: bigint,
      registry: string,
    ) => Promise<void>
    AddressUpdatePending: (
      regId: bigint,
      description: string,
      newAddr: `0x${string}`,
      prevAddr: `0x${string}`,
      version: bigint,
      confirmBlock: bigint,
      registry: string,
    ) => Promise<void>
    AddressUpdateConfirmed: (
      regId: bigint,
      description: string,
      newAddr: `0x${string}`,
      prevAddr: `0x${string}`,
      version: bigint,
      registry: string,
    ) => Promise<void>
    AddressUpdateCancelled: (
      regId: bigint,
      description: string,
      newAddr: `0x${string}`,
      prevAddr: `0x${string}`,
      initiatedBlock: bigint,
      confirmBlock: bigint,
      registry: string,
    ) => Promise<void>
    AddressDisablePending: (
      regId: bigint,
      description: string,
      addr: `0x${string}`,
      version: bigint,
      confirmBlock: bigint,
      registry: string,
    ) => Promise<void>
    AddressDisableConfirmed: (
      regId: bigint,
      description: string,
      addr: `0x${string}`,
      version: bigint,
      registry: string,
    ) => Promise<void>
    AddressDisableCancelled: (
      regId: bigint,
      description: string,
      addr: `0x${string}`,
      initiatedBlock: bigint,
      confirmBlock: bigint,
      registry: string,
    ) => Promise<void>
  }
}

export type Calls = keyof Contract['calls']
export type Request<M extends Calls> = {
  contractName: 'UndyHq'
  method: M
  args: ExtractArgs<Contract['calls'][M]>
  address: Address | undefined
  deployAddress: Address | undefined
  defaultValue: Awaited<ReturnType<Contract['calls'][M]>> | undefined
  getAbi: () => typeof abi
  with: (options: { contractAddress?: Address; defaultValue?: Awaited<ReturnType<Contract['calls'][M]>> }) => Request<M>
  defaultTo: (defaultValue: Awaited<ReturnType<Contract['calls'][M]>>) => Request<M>
  at: (address: Address) => Request<M>
}
export type CallReturn<M extends Calls> = NonNullable<Request<M>['defaultValue']>

function getRequest<M extends Calls>(
  method: M,
  args: ExtractArgs<Contract['calls'][M]>,
  contractAddressOrOptions?:
    | Address
    | {
        contractAddress?: Address
        defaultValue?: Awaited<ReturnType<Contract['calls'][M]>>
      },
): Request<M> {
  const address =
    typeof contractAddressOrOptions === 'string' ? contractAddressOrOptions : contractAddressOrOptions?.contractAddress
  const defaultValue = typeof contractAddressOrOptions === 'string' ? undefined : contractAddressOrOptions?.defaultValue

  const call = {
    contractName: 'UndyHq' as const,
    method,
    args,
    address,
    deployAddress,
    defaultValue,
    getAbi: () => abi,
    with: (options: { contractAddress?: Address; defaultValue?: Awaited<ReturnType<Contract['calls'][M]>> }) => {
      call.address = options.contractAddress
      call.defaultValue = options.defaultValue
      return call as Request<M>
    },
    defaultTo: (defaultValue: Awaited<ReturnType<Contract['calls'][M]>>) => {
      call.defaultValue = defaultValue
      return call as Request<M>
    },
    at: (address: Address) => {
      call.address = address
      return call as Request<M>
    },
  } as Request<M>

  return call
}

type CallType = {
  [K in Calls]: (...args: ExtractArgs<Contract['calls'][K]>) => ReturnType<typeof getRequest<K>>
}

export const call: CallType = {
  getUndyHqFromGov: (...args: ExtractArgs<Contract['calls']['getUndyHqFromGov']>) =>
    getRequest('getUndyHqFromGov', args),
  canGovern: (...args: ExtractArgs<Contract['calls']['canGovern']>) => getRequest('canGovern', args),
  getGovernors: (...args: ExtractArgs<Contract['calls']['getGovernors']>) => getRequest('getGovernors', args),
  hasPendingGovChange: (...args: ExtractArgs<Contract['calls']['hasPendingGovChange']>) =>
    getRequest('hasPendingGovChange', args),
  isValidGovTimeLock: (...args: ExtractArgs<Contract['calls']['isValidGovTimeLock']>) =>
    getRequest('isValidGovTimeLock', args),
  minGovChangeTimeLock: (...args: ExtractArgs<Contract['calls']['minGovChangeTimeLock']>) =>
    getRequest('minGovChangeTimeLock', args),
  maxGovChangeTimeLock: (...args: ExtractArgs<Contract['calls']['maxGovChangeTimeLock']>) =>
    getRequest('maxGovChangeTimeLock', args),
  governance: (...args: ExtractArgs<Contract['calls']['governance']>) => getRequest('governance', args),
  pendingGov: (...args: ExtractArgs<Contract['calls']['pendingGov']>) => getRequest('pendingGov', args),
  numGovChanges: (...args: ExtractArgs<Contract['calls']['numGovChanges']>) => getRequest('numGovChanges', args),
  govChangeTimeLock: (...args: ExtractArgs<Contract['calls']['govChangeTimeLock']>) =>
    getRequest('govChangeTimeLock', args),
  getRegistryDescription: (...args: ExtractArgs<Contract['calls']['getRegistryDescription']>) =>
    getRequest('getRegistryDescription', args),
  isValidNewAddress: (...args: ExtractArgs<Contract['calls']['isValidNewAddress']>) =>
    getRequest('isValidNewAddress', args),
  isValidAddressUpdate: (...args: ExtractArgs<Contract['calls']['isValidAddressUpdate']>) =>
    getRequest('isValidAddressUpdate', args),
  isValidAddressDisable: (...args: ExtractArgs<Contract['calls']['isValidAddressDisable']>) =>
    getRequest('isValidAddressDisable', args),
  isValidRegistryTimeLock: (...args: ExtractArgs<Contract['calls']['isValidRegistryTimeLock']>) =>
    getRequest('isValidRegistryTimeLock', args),
  minRegistryTimeLock: (...args: ExtractArgs<Contract['calls']['minRegistryTimeLock']>) =>
    getRequest('minRegistryTimeLock', args),
  maxRegistryTimeLock: (...args: ExtractArgs<Contract['calls']['maxRegistryTimeLock']>) =>
    getRequest('maxRegistryTimeLock', args),
  isValidAddr: (...args: ExtractArgs<Contract['calls']['isValidAddr']>) => getRequest('isValidAddr', args),
  isValidRegId: (...args: ExtractArgs<Contract['calls']['isValidRegId']>) => getRequest('isValidRegId', args),
  getRegId: (...args: ExtractArgs<Contract['calls']['getRegId']>) => getRequest('getRegId', args),
  getAddr: (...args: ExtractArgs<Contract['calls']['getAddr']>) => getRequest('getAddr', args),
  getAddrInfo: (...args: ExtractArgs<Contract['calls']['getAddrInfo']>) => getRequest('getAddrInfo', args),
  getAddrDescription: (...args: ExtractArgs<Contract['calls']['getAddrDescription']>) =>
    getRequest('getAddrDescription', args),
  getNumAddrs: (...args: ExtractArgs<Contract['calls']['getNumAddrs']>) => getRequest('getNumAddrs', args),
  getLastAddr: (...args: ExtractArgs<Contract['calls']['getLastAddr']>) => getRequest('getLastAddr', args),
  getLastRegId: (...args: ExtractArgs<Contract['calls']['getLastRegId']>) => getRequest('getLastRegId', args),
  registryChangeTimeLock: (...args: ExtractArgs<Contract['calls']['registryChangeTimeLock']>) =>
    getRequest('registryChangeTimeLock', args),
  addrInfo: (...args: ExtractArgs<Contract['calls']['addrInfo']>) => getRequest('addrInfo', args),
  addrToRegId: (...args: ExtractArgs<Contract['calls']['addrToRegId']>) => getRequest('addrToRegId', args),
  numAddrs: (...args: ExtractArgs<Contract['calls']['numAddrs']>) => getRequest('numAddrs', args),
  pendingNewAddr: (...args: ExtractArgs<Contract['calls']['pendingNewAddr']>) => getRequest('pendingNewAddr', args),
  pendingAddrUpdate: (...args: ExtractArgs<Contract['calls']['pendingAddrUpdate']>) =>
    getRequest('pendingAddrUpdate', args),
  pendingAddrDisable: (...args: ExtractArgs<Contract['calls']['pendingAddrDisable']>) =>
    getRequest('pendingAddrDisable', args),
  hasPendingHqConfigChange: (...args: ExtractArgs<Contract['calls']['hasPendingHqConfigChange']>) =>
    getRequest('hasPendingHqConfigChange', args),
  isValidHqConfig: (...args: ExtractArgs<Contract['calls']['isValidHqConfig']>) => getRequest('isValidHqConfig', args),
  canMintUndy: (...args: ExtractArgs<Contract['calls']['canMintUndy']>) => getRequest('canMintUndy', args),
  canSetTokenBlacklist: (...args: ExtractArgs<Contract['calls']['canSetTokenBlacklist']>) =>
    getRequest('canSetTokenBlacklist', args),
  undyToken: (...args: ExtractArgs<Contract['calls']['undyToken']>) => getRequest('undyToken', args),
  mintEnabled: (...args: ExtractArgs<Contract['calls']['mintEnabled']>) => getRequest('mintEnabled', args),
  hqConfig: (...args: ExtractArgs<Contract['calls']['hqConfig']>) => getRequest('hqConfig', args),
  pendingHqConfig: (...args: ExtractArgs<Contract['calls']['pendingHqConfig']>) => getRequest('pendingHqConfig', args),
}

export type Mutations = keyof Contract['mutations']
function getMutation<M extends Mutations>(functionName: M) {
  return {
    contractName: 'UndyHq' as const,
    functionName,
    deployAddress,
    argsType: undefined as ExtractArgs<Contract['mutations'][M]> | undefined,
    getAbi: () => abi,
  }
}

export const mutation: {
  [K in Mutations]: {
    contractName: 'UndyHq'
    deployAddress: Address | undefined
    getAbi: () => typeof abi
    functionName: K
    argsType: ExtractArgs<Contract['mutations'][K]> | undefined
  }
} = {
  startGovernanceChange: getMutation('startGovernanceChange'),
  confirmGovernanceChange: getMutation('confirmGovernanceChange'),
  cancelGovernanceChange: getMutation('cancelGovernanceChange'),
  relinquishGov: getMutation('relinquishGov'),
  setGovTimeLock: getMutation('setGovTimeLock'),
  finishUndyHqSetup: getMutation('finishUndyHqSetup'),
  setRegistryTimeLock: getMutation('setRegistryTimeLock'),
  setRegistryTimeLockAfterSetup: getMutation('setRegistryTimeLockAfterSetup'),
  startAddNewAddressToRegistry: getMutation('startAddNewAddressToRegistry'),
  confirmNewAddressToRegistry: getMutation('confirmNewAddressToRegistry'),
  cancelNewAddressToRegistry: getMutation('cancelNewAddressToRegistry'),
  startAddressUpdateToRegistry: getMutation('startAddressUpdateToRegistry'),
  confirmAddressUpdateToRegistry: getMutation('confirmAddressUpdateToRegistry'),
  cancelAddressUpdateToRegistry: getMutation('cancelAddressUpdateToRegistry'),
  startAddressDisableInRegistry: getMutation('startAddressDisableInRegistry'),
  confirmAddressDisableInRegistry: getMutation('confirmAddressDisableInRegistry'),
  cancelAddressDisableInRegistry: getMutation('cancelAddressDisableInRegistry'),
  initiateHqConfigChange: getMutation('initiateHqConfigChange'),
  confirmHqConfigChange: getMutation('confirmHqConfigChange'),
  cancelHqConfigChange: getMutation('cancelHqConfigChange'),
  setUndyToken: getMutation('setUndyToken'),
  setMintingEnabled: getMutation('setMintingEnabled'),
  recoverFunds: getMutation('recoverFunds'),
  recoverFundsMany: getMutation('recoverFundsMany'),
}

export type ParsedEvent<T extends keyof Contract['events']> = {
  event: RpcLog | Log
  parsed: ParseEventLogsReturnType<typeof abi, T>
}

export function parseEvents<T extends keyof Contract['events']>(
  eventName: T,
  events: (RpcLog | Log)[],
): ParsedEvent<T>[] {
  return events.map((event) => {
    return {
      event,
      parsed: parseEventLogs({
        abi,
        eventName,
        logs: [event],
      }),
    }
  })
}

export function getEventTopic<T extends keyof Contract['events']>(eventName: T): Address {
  return encodeEventTopics({ abi, eventName })[0] as Address
}

export type SDK = {
  deployAddress: Address | undefined
  abi: typeof abi
  events: {
    HqConfigChangeInitiated: {
      topic: Address
      parse: (events: (RpcLog | Log)[]) => ParsedEvent<'HqConfigChangeInitiated'>[]
    }
    HqConfigChangeConfirmed: {
      topic: Address
      parse: (events: (RpcLog | Log)[]) => ParsedEvent<'HqConfigChangeConfirmed'>[]
    }
    HqConfigChangeCancelled: {
      topic: Address
      parse: (events: (RpcLog | Log)[]) => ParsedEvent<'HqConfigChangeCancelled'>[]
    }
    UndyHqFundsRecovered: { topic: Address; parse: (events: (RpcLog | Log)[]) => ParsedEvent<'UndyHqFundsRecovered'>[] }
    UndyTokenSet: { topic: Address; parse: (events: (RpcLog | Log)[]) => ParsedEvent<'UndyTokenSet'>[] }
    MintingEnabled: { topic: Address; parse: (events: (RpcLog | Log)[]) => ParsedEvent<'MintingEnabled'>[] }
    GovChangeTimeLockModified: {
      topic: Address
      parse: (events: (RpcLog | Log)[]) => ParsedEvent<'GovChangeTimeLockModified'>[]
    }
    RegistryTimeLockModified: {
      topic: Address
      parse: (events: (RpcLog | Log)[]) => ParsedEvent<'RegistryTimeLockModified'>[]
    }
    GovChangeStarted: { topic: Address; parse: (events: (RpcLog | Log)[]) => ParsedEvent<'GovChangeStarted'>[] }
    GovChangeConfirmed: { topic: Address; parse: (events: (RpcLog | Log)[]) => ParsedEvent<'GovChangeConfirmed'>[] }
    GovChangeCancelled: { topic: Address; parse: (events: (RpcLog | Log)[]) => ParsedEvent<'GovChangeCancelled'>[] }
    GovRelinquished: { topic: Address; parse: (events: (RpcLog | Log)[]) => ParsedEvent<'GovRelinquished'>[] }
    UndyHqSetupFinished: { topic: Address; parse: (events: (RpcLog | Log)[]) => ParsedEvent<'UndyHqSetupFinished'>[] }
    NewAddressPending: { topic: Address; parse: (events: (RpcLog | Log)[]) => ParsedEvent<'NewAddressPending'>[] }
    NewAddressConfirmed: { topic: Address; parse: (events: (RpcLog | Log)[]) => ParsedEvent<'NewAddressConfirmed'>[] }
    NewAddressCancelled: { topic: Address; parse: (events: (RpcLog | Log)[]) => ParsedEvent<'NewAddressCancelled'>[] }
    AddressUpdatePending: { topic: Address; parse: (events: (RpcLog | Log)[]) => ParsedEvent<'AddressUpdatePending'>[] }
    AddressUpdateConfirmed: {
      topic: Address
      parse: (events: (RpcLog | Log)[]) => ParsedEvent<'AddressUpdateConfirmed'>[]
    }
    AddressUpdateCancelled: {
      topic: Address
      parse: (events: (RpcLog | Log)[]) => ParsedEvent<'AddressUpdateCancelled'>[]
    }
    AddressDisablePending: {
      topic: Address
      parse: (events: (RpcLog | Log)[]) => ParsedEvent<'AddressDisablePending'>[]
    }
    AddressDisableConfirmed: {
      topic: Address
      parse: (events: (RpcLog | Log)[]) => ParsedEvent<'AddressDisableConfirmed'>[]
    }
    AddressDisableCancelled: {
      topic: Address
      parse: (events: (RpcLog | Log)[]) => ParsedEvent<'AddressDisableCancelled'>[]
    }
  }
  getUndyHqFromGov: (
    ...args: ExtractArgs<Contract['calls']['getUndyHqFromGov']>
  ) => Promise<CallReturn<'getUndyHqFromGov'>>
  canGovern: (...args: ExtractArgs<Contract['calls']['canGovern']>) => Promise<CallReturn<'canGovern'>>
  getGovernors: (...args: ExtractArgs<Contract['calls']['getGovernors']>) => Promise<CallReturn<'getGovernors'>>
  hasPendingGovChange: (
    ...args: ExtractArgs<Contract['calls']['hasPendingGovChange']>
  ) => Promise<CallReturn<'hasPendingGovChange'>>
  isValidGovTimeLock: (
    ...args: ExtractArgs<Contract['calls']['isValidGovTimeLock']>
  ) => Promise<CallReturn<'isValidGovTimeLock'>>
  minGovChangeTimeLock: (
    ...args: ExtractArgs<Contract['calls']['minGovChangeTimeLock']>
  ) => Promise<CallReturn<'minGovChangeTimeLock'>>
  maxGovChangeTimeLock: (
    ...args: ExtractArgs<Contract['calls']['maxGovChangeTimeLock']>
  ) => Promise<CallReturn<'maxGovChangeTimeLock'>>
  governance: (...args: ExtractArgs<Contract['calls']['governance']>) => Promise<CallReturn<'governance'>>
  pendingGov: (...args: ExtractArgs<Contract['calls']['pendingGov']>) => Promise<CallReturn<'pendingGov'>>
  numGovChanges: (...args: ExtractArgs<Contract['calls']['numGovChanges']>) => Promise<CallReturn<'numGovChanges'>>
  govChangeTimeLock: (
    ...args: ExtractArgs<Contract['calls']['govChangeTimeLock']>
  ) => Promise<CallReturn<'govChangeTimeLock'>>
  getRegistryDescription: (
    ...args: ExtractArgs<Contract['calls']['getRegistryDescription']>
  ) => Promise<CallReturn<'getRegistryDescription'>>
  isValidNewAddress: (
    ...args: ExtractArgs<Contract['calls']['isValidNewAddress']>
  ) => Promise<CallReturn<'isValidNewAddress'>>
  isValidAddressUpdate: (
    ...args: ExtractArgs<Contract['calls']['isValidAddressUpdate']>
  ) => Promise<CallReturn<'isValidAddressUpdate'>>
  isValidAddressDisable: (
    ...args: ExtractArgs<Contract['calls']['isValidAddressDisable']>
  ) => Promise<CallReturn<'isValidAddressDisable'>>
  isValidRegistryTimeLock: (
    ...args: ExtractArgs<Contract['calls']['isValidRegistryTimeLock']>
  ) => Promise<CallReturn<'isValidRegistryTimeLock'>>
  minRegistryTimeLock: (
    ...args: ExtractArgs<Contract['calls']['minRegistryTimeLock']>
  ) => Promise<CallReturn<'minRegistryTimeLock'>>
  maxRegistryTimeLock: (
    ...args: ExtractArgs<Contract['calls']['maxRegistryTimeLock']>
  ) => Promise<CallReturn<'maxRegistryTimeLock'>>
  isValidAddr: (...args: ExtractArgs<Contract['calls']['isValidAddr']>) => Promise<CallReturn<'isValidAddr'>>
  isValidRegId: (...args: ExtractArgs<Contract['calls']['isValidRegId']>) => Promise<CallReturn<'isValidRegId'>>
  getRegId: (...args: ExtractArgs<Contract['calls']['getRegId']>) => Promise<CallReturn<'getRegId'>>
  getAddr: (...args: ExtractArgs<Contract['calls']['getAddr']>) => Promise<CallReturn<'getAddr'>>
  getAddrInfo: (...args: ExtractArgs<Contract['calls']['getAddrInfo']>) => Promise<CallReturn<'getAddrInfo'>>
  getAddrDescription: (
    ...args: ExtractArgs<Contract['calls']['getAddrDescription']>
  ) => Promise<CallReturn<'getAddrDescription'>>
  getNumAddrs: (...args: ExtractArgs<Contract['calls']['getNumAddrs']>) => Promise<CallReturn<'getNumAddrs'>>
  getLastAddr: (...args: ExtractArgs<Contract['calls']['getLastAddr']>) => Promise<CallReturn<'getLastAddr'>>
  getLastRegId: (...args: ExtractArgs<Contract['calls']['getLastRegId']>) => Promise<CallReturn<'getLastRegId'>>
  registryChangeTimeLock: (
    ...args: ExtractArgs<Contract['calls']['registryChangeTimeLock']>
  ) => Promise<CallReturn<'registryChangeTimeLock'>>
  addrInfo: (...args: ExtractArgs<Contract['calls']['addrInfo']>) => Promise<CallReturn<'addrInfo'>>
  addrToRegId: (...args: ExtractArgs<Contract['calls']['addrToRegId']>) => Promise<CallReturn<'addrToRegId'>>
  numAddrs: (...args: ExtractArgs<Contract['calls']['numAddrs']>) => Promise<CallReturn<'numAddrs'>>
  pendingNewAddr: (...args: ExtractArgs<Contract['calls']['pendingNewAddr']>) => Promise<CallReturn<'pendingNewAddr'>>
  pendingAddrUpdate: (
    ...args: ExtractArgs<Contract['calls']['pendingAddrUpdate']>
  ) => Promise<CallReturn<'pendingAddrUpdate'>>
  pendingAddrDisable: (
    ...args: ExtractArgs<Contract['calls']['pendingAddrDisable']>
  ) => Promise<CallReturn<'pendingAddrDisable'>>
  hasPendingHqConfigChange: (
    ...args: ExtractArgs<Contract['calls']['hasPendingHqConfigChange']>
  ) => Promise<CallReturn<'hasPendingHqConfigChange'>>
  isValidHqConfig: (
    ...args: ExtractArgs<Contract['calls']['isValidHqConfig']>
  ) => Promise<CallReturn<'isValidHqConfig'>>
  canMintUndy: (...args: ExtractArgs<Contract['calls']['canMintUndy']>) => Promise<CallReturn<'canMintUndy'>>
  canSetTokenBlacklist: (
    ...args: ExtractArgs<Contract['calls']['canSetTokenBlacklist']>
  ) => Promise<CallReturn<'canSetTokenBlacklist'>>
  undyToken: (...args: ExtractArgs<Contract['calls']['undyToken']>) => Promise<CallReturn<'undyToken'>>
  mintEnabled: (...args: ExtractArgs<Contract['calls']['mintEnabled']>) => Promise<CallReturn<'mintEnabled'>>
  hqConfig: (...args: ExtractArgs<Contract['calls']['hqConfig']>) => Promise<CallReturn<'hqConfig'>>
  pendingHqConfig: (
    ...args: ExtractArgs<Contract['calls']['pendingHqConfig']>
  ) => Promise<CallReturn<'pendingHqConfig'>>
  startGovernanceChange: (...args: ExtractArgs<Contract['mutations']['startGovernanceChange']>) => Promise<Address>
  confirmGovernanceChange: (...args: ExtractArgs<Contract['mutations']['confirmGovernanceChange']>) => Promise<Address>
  cancelGovernanceChange: (...args: ExtractArgs<Contract['mutations']['cancelGovernanceChange']>) => Promise<Address>
  relinquishGov: (...args: ExtractArgs<Contract['mutations']['relinquishGov']>) => Promise<Address>
  setGovTimeLock: (...args: ExtractArgs<Contract['mutations']['setGovTimeLock']>) => Promise<Address>
  finishUndyHqSetup: (...args: ExtractArgs<Contract['mutations']['finishUndyHqSetup']>) => Promise<Address>
  setRegistryTimeLock: (...args: ExtractArgs<Contract['mutations']['setRegistryTimeLock']>) => Promise<Address>
  setRegistryTimeLockAfterSetup: (
    ...args: ExtractArgs<Contract['mutations']['setRegistryTimeLockAfterSetup']>
  ) => Promise<Address>
  startAddNewAddressToRegistry: (
    ...args: ExtractArgs<Contract['mutations']['startAddNewAddressToRegistry']>
  ) => Promise<Address>
  confirmNewAddressToRegistry: (
    ...args: ExtractArgs<Contract['mutations']['confirmNewAddressToRegistry']>
  ) => Promise<Address>
  cancelNewAddressToRegistry: (
    ...args: ExtractArgs<Contract['mutations']['cancelNewAddressToRegistry']>
  ) => Promise<Address>
  startAddressUpdateToRegistry: (
    ...args: ExtractArgs<Contract['mutations']['startAddressUpdateToRegistry']>
  ) => Promise<Address>
  confirmAddressUpdateToRegistry: (
    ...args: ExtractArgs<Contract['mutations']['confirmAddressUpdateToRegistry']>
  ) => Promise<Address>
  cancelAddressUpdateToRegistry: (
    ...args: ExtractArgs<Contract['mutations']['cancelAddressUpdateToRegistry']>
  ) => Promise<Address>
  startAddressDisableInRegistry: (
    ...args: ExtractArgs<Contract['mutations']['startAddressDisableInRegistry']>
  ) => Promise<Address>
  confirmAddressDisableInRegistry: (
    ...args: ExtractArgs<Contract['mutations']['confirmAddressDisableInRegistry']>
  ) => Promise<Address>
  cancelAddressDisableInRegistry: (
    ...args: ExtractArgs<Contract['mutations']['cancelAddressDisableInRegistry']>
  ) => Promise<Address>
  initiateHqConfigChange: (...args: ExtractArgs<Contract['mutations']['initiateHqConfigChange']>) => Promise<Address>
  confirmHqConfigChange: (...args: ExtractArgs<Contract['mutations']['confirmHqConfigChange']>) => Promise<Address>
  cancelHqConfigChange: (...args: ExtractArgs<Contract['mutations']['cancelHqConfigChange']>) => Promise<Address>
  setUndyToken: (...args: ExtractArgs<Contract['mutations']['setUndyToken']>) => Promise<Address>
  setMintingEnabled: (...args: ExtractArgs<Contract['mutations']['setMintingEnabled']>) => Promise<Address>
  recoverFunds: (...args: ExtractArgs<Contract['mutations']['recoverFunds']>) => Promise<Address>
  recoverFundsMany: (...args: ExtractArgs<Contract['mutations']['recoverFundsMany']>) => Promise<Address>
}

export function toSdk(
  publicClient?: PublicClient,
  walletClient?: WalletClient,
  addressResolver?: AddressResolverFunction,
): SDK {
  return {
    deployAddress,
    abi,

    events: {
      HqConfigChangeInitiated: {
        topic: getEventTopic('HqConfigChangeInitiated'),
        parse: (events: (RpcLog | Log)[]) => parseEvents('HqConfigChangeInitiated', events),
      },
      HqConfigChangeConfirmed: {
        topic: getEventTopic('HqConfigChangeConfirmed'),
        parse: (events: (RpcLog | Log)[]) => parseEvents('HqConfigChangeConfirmed', events),
      },
      HqConfigChangeCancelled: {
        topic: getEventTopic('HqConfigChangeCancelled'),
        parse: (events: (RpcLog | Log)[]) => parseEvents('HqConfigChangeCancelled', events),
      },
      UndyHqFundsRecovered: {
        topic: getEventTopic('UndyHqFundsRecovered'),
        parse: (events: (RpcLog | Log)[]) => parseEvents('UndyHqFundsRecovered', events),
      },
      UndyTokenSet: {
        topic: getEventTopic('UndyTokenSet'),
        parse: (events: (RpcLog | Log)[]) => parseEvents('UndyTokenSet', events),
      },
      MintingEnabled: {
        topic: getEventTopic('MintingEnabled'),
        parse: (events: (RpcLog | Log)[]) => parseEvents('MintingEnabled', events),
      },
      GovChangeTimeLockModified: {
        topic: getEventTopic('GovChangeTimeLockModified'),
        parse: (events: (RpcLog | Log)[]) => parseEvents('GovChangeTimeLockModified', events),
      },
      RegistryTimeLockModified: {
        topic: getEventTopic('RegistryTimeLockModified'),
        parse: (events: (RpcLog | Log)[]) => parseEvents('RegistryTimeLockModified', events),
      },
      GovChangeStarted: {
        topic: getEventTopic('GovChangeStarted'),
        parse: (events: (RpcLog | Log)[]) => parseEvents('GovChangeStarted', events),
      },
      GovChangeConfirmed: {
        topic: getEventTopic('GovChangeConfirmed'),
        parse: (events: (RpcLog | Log)[]) => parseEvents('GovChangeConfirmed', events),
      },
      GovChangeCancelled: {
        topic: getEventTopic('GovChangeCancelled'),
        parse: (events: (RpcLog | Log)[]) => parseEvents('GovChangeCancelled', events),
      },
      GovRelinquished: {
        topic: getEventTopic('GovRelinquished'),
        parse: (events: (RpcLog | Log)[]) => parseEvents('GovRelinquished', events),
      },
      UndyHqSetupFinished: {
        topic: getEventTopic('UndyHqSetupFinished'),
        parse: (events: (RpcLog | Log)[]) => parseEvents('UndyHqSetupFinished', events),
      },
      NewAddressPending: {
        topic: getEventTopic('NewAddressPending'),
        parse: (events: (RpcLog | Log)[]) => parseEvents('NewAddressPending', events),
      },
      NewAddressConfirmed: {
        topic: getEventTopic('NewAddressConfirmed'),
        parse: (events: (RpcLog | Log)[]) => parseEvents('NewAddressConfirmed', events),
      },
      NewAddressCancelled: {
        topic: getEventTopic('NewAddressCancelled'),
        parse: (events: (RpcLog | Log)[]) => parseEvents('NewAddressCancelled', events),
      },
      AddressUpdatePending: {
        topic: getEventTopic('AddressUpdatePending'),
        parse: (events: (RpcLog | Log)[]) => parseEvents('AddressUpdatePending', events),
      },
      AddressUpdateConfirmed: {
        topic: getEventTopic('AddressUpdateConfirmed'),
        parse: (events: (RpcLog | Log)[]) => parseEvents('AddressUpdateConfirmed', events),
      },
      AddressUpdateCancelled: {
        topic: getEventTopic('AddressUpdateCancelled'),
        parse: (events: (RpcLog | Log)[]) => parseEvents('AddressUpdateCancelled', events),
      },
      AddressDisablePending: {
        topic: getEventTopic('AddressDisablePending'),
        parse: (events: (RpcLog | Log)[]) => parseEvents('AddressDisablePending', events),
      },
      AddressDisableConfirmed: {
        topic: getEventTopic('AddressDisableConfirmed'),
        parse: (events: (RpcLog | Log)[]) => parseEvents('AddressDisableConfirmed', events),
      },
      AddressDisableCancelled: {
        topic: getEventTopic('AddressDisableCancelled'),
        parse: (events: (RpcLog | Log)[]) => parseEvents('AddressDisableCancelled', events),
      },
    },
    // Queries
    getUndyHqFromGov: (...args: ExtractArgs<Contract['calls']['getUndyHqFromGov']>) =>
      singleQuery(publicClient!, call.getUndyHqFromGov(...args), {}, addressResolver) as Promise<
        CallReturn<'getUndyHqFromGov'>
      >,
    canGovern: (...args: ExtractArgs<Contract['calls']['canGovern']>) =>
      singleQuery(publicClient!, call.canGovern(...args), {}, addressResolver) as Promise<CallReturn<'canGovern'>>,
    getGovernors: (...args: ExtractArgs<Contract['calls']['getGovernors']>) =>
      singleQuery(publicClient!, call.getGovernors(...args), {}, addressResolver) as Promise<
        CallReturn<'getGovernors'>
      >,
    hasPendingGovChange: (...args: ExtractArgs<Contract['calls']['hasPendingGovChange']>) =>
      singleQuery(publicClient!, call.hasPendingGovChange(...args), {}, addressResolver) as Promise<
        CallReturn<'hasPendingGovChange'>
      >,
    isValidGovTimeLock: (...args: ExtractArgs<Contract['calls']['isValidGovTimeLock']>) =>
      singleQuery(publicClient!, call.isValidGovTimeLock(...args), {}, addressResolver) as Promise<
        CallReturn<'isValidGovTimeLock'>
      >,
    minGovChangeTimeLock: (...args: ExtractArgs<Contract['calls']['minGovChangeTimeLock']>) =>
      singleQuery(publicClient!, call.minGovChangeTimeLock(...args), {}, addressResolver) as Promise<
        CallReturn<'minGovChangeTimeLock'>
      >,
    maxGovChangeTimeLock: (...args: ExtractArgs<Contract['calls']['maxGovChangeTimeLock']>) =>
      singleQuery(publicClient!, call.maxGovChangeTimeLock(...args), {}, addressResolver) as Promise<
        CallReturn<'maxGovChangeTimeLock'>
      >,
    governance: (...args: ExtractArgs<Contract['calls']['governance']>) =>
      singleQuery(publicClient!, call.governance(...args), {}, addressResolver) as Promise<CallReturn<'governance'>>,
    pendingGov: (...args: ExtractArgs<Contract['calls']['pendingGov']>) =>
      singleQuery(publicClient!, call.pendingGov(...args), {}, addressResolver) as Promise<CallReturn<'pendingGov'>>,
    numGovChanges: (...args: ExtractArgs<Contract['calls']['numGovChanges']>) =>
      singleQuery(publicClient!, call.numGovChanges(...args), {}, addressResolver) as Promise<
        CallReturn<'numGovChanges'>
      >,
    govChangeTimeLock: (...args: ExtractArgs<Contract['calls']['govChangeTimeLock']>) =>
      singleQuery(publicClient!, call.govChangeTimeLock(...args), {}, addressResolver) as Promise<
        CallReturn<'govChangeTimeLock'>
      >,
    getRegistryDescription: (...args: ExtractArgs<Contract['calls']['getRegistryDescription']>) =>
      singleQuery(publicClient!, call.getRegistryDescription(...args), {}, addressResolver) as Promise<
        CallReturn<'getRegistryDescription'>
      >,
    isValidNewAddress: (...args: ExtractArgs<Contract['calls']['isValidNewAddress']>) =>
      singleQuery(publicClient!, call.isValidNewAddress(...args), {}, addressResolver) as Promise<
        CallReturn<'isValidNewAddress'>
      >,
    isValidAddressUpdate: (...args: ExtractArgs<Contract['calls']['isValidAddressUpdate']>) =>
      singleQuery(publicClient!, call.isValidAddressUpdate(...args), {}, addressResolver) as Promise<
        CallReturn<'isValidAddressUpdate'>
      >,
    isValidAddressDisable: (...args: ExtractArgs<Contract['calls']['isValidAddressDisable']>) =>
      singleQuery(publicClient!, call.isValidAddressDisable(...args), {}, addressResolver) as Promise<
        CallReturn<'isValidAddressDisable'>
      >,
    isValidRegistryTimeLock: (...args: ExtractArgs<Contract['calls']['isValidRegistryTimeLock']>) =>
      singleQuery(publicClient!, call.isValidRegistryTimeLock(...args), {}, addressResolver) as Promise<
        CallReturn<'isValidRegistryTimeLock'>
      >,
    minRegistryTimeLock: (...args: ExtractArgs<Contract['calls']['minRegistryTimeLock']>) =>
      singleQuery(publicClient!, call.minRegistryTimeLock(...args), {}, addressResolver) as Promise<
        CallReturn<'minRegistryTimeLock'>
      >,
    maxRegistryTimeLock: (...args: ExtractArgs<Contract['calls']['maxRegistryTimeLock']>) =>
      singleQuery(publicClient!, call.maxRegistryTimeLock(...args), {}, addressResolver) as Promise<
        CallReturn<'maxRegistryTimeLock'>
      >,
    isValidAddr: (...args: ExtractArgs<Contract['calls']['isValidAddr']>) =>
      singleQuery(publicClient!, call.isValidAddr(...args), {}, addressResolver) as Promise<CallReturn<'isValidAddr'>>,
    isValidRegId: (...args: ExtractArgs<Contract['calls']['isValidRegId']>) =>
      singleQuery(publicClient!, call.isValidRegId(...args), {}, addressResolver) as Promise<
        CallReturn<'isValidRegId'>
      >,
    getRegId: (...args: ExtractArgs<Contract['calls']['getRegId']>) =>
      singleQuery(publicClient!, call.getRegId(...args), {}, addressResolver) as Promise<CallReturn<'getRegId'>>,
    getAddr: (...args: ExtractArgs<Contract['calls']['getAddr']>) =>
      singleQuery(publicClient!, call.getAddr(...args), {}, addressResolver) as Promise<CallReturn<'getAddr'>>,
    getAddrInfo: (...args: ExtractArgs<Contract['calls']['getAddrInfo']>) =>
      singleQuery(publicClient!, call.getAddrInfo(...args), {}, addressResolver) as Promise<CallReturn<'getAddrInfo'>>,
    getAddrDescription: (...args: ExtractArgs<Contract['calls']['getAddrDescription']>) =>
      singleQuery(publicClient!, call.getAddrDescription(...args), {}, addressResolver) as Promise<
        CallReturn<'getAddrDescription'>
      >,
    getNumAddrs: (...args: ExtractArgs<Contract['calls']['getNumAddrs']>) =>
      singleQuery(publicClient!, call.getNumAddrs(...args), {}, addressResolver) as Promise<CallReturn<'getNumAddrs'>>,
    getLastAddr: (...args: ExtractArgs<Contract['calls']['getLastAddr']>) =>
      singleQuery(publicClient!, call.getLastAddr(...args), {}, addressResolver) as Promise<CallReturn<'getLastAddr'>>,
    getLastRegId: (...args: ExtractArgs<Contract['calls']['getLastRegId']>) =>
      singleQuery(publicClient!, call.getLastRegId(...args), {}, addressResolver) as Promise<
        CallReturn<'getLastRegId'>
      >,
    registryChangeTimeLock: (...args: ExtractArgs<Contract['calls']['registryChangeTimeLock']>) =>
      singleQuery(publicClient!, call.registryChangeTimeLock(...args), {}, addressResolver) as Promise<
        CallReturn<'registryChangeTimeLock'>
      >,
    addrInfo: (...args: ExtractArgs<Contract['calls']['addrInfo']>) =>
      singleQuery(publicClient!, call.addrInfo(...args), {}, addressResolver) as Promise<CallReturn<'addrInfo'>>,
    addrToRegId: (...args: ExtractArgs<Contract['calls']['addrToRegId']>) =>
      singleQuery(publicClient!, call.addrToRegId(...args), {}, addressResolver) as Promise<CallReturn<'addrToRegId'>>,
    numAddrs: (...args: ExtractArgs<Contract['calls']['numAddrs']>) =>
      singleQuery(publicClient!, call.numAddrs(...args), {}, addressResolver) as Promise<CallReturn<'numAddrs'>>,
    pendingNewAddr: (...args: ExtractArgs<Contract['calls']['pendingNewAddr']>) =>
      singleQuery(publicClient!, call.pendingNewAddr(...args), {}, addressResolver) as Promise<
        CallReturn<'pendingNewAddr'>
      >,
    pendingAddrUpdate: (...args: ExtractArgs<Contract['calls']['pendingAddrUpdate']>) =>
      singleQuery(publicClient!, call.pendingAddrUpdate(...args), {}, addressResolver) as Promise<
        CallReturn<'pendingAddrUpdate'>
      >,
    pendingAddrDisable: (...args: ExtractArgs<Contract['calls']['pendingAddrDisable']>) =>
      singleQuery(publicClient!, call.pendingAddrDisable(...args), {}, addressResolver) as Promise<
        CallReturn<'pendingAddrDisable'>
      >,
    hasPendingHqConfigChange: (...args: ExtractArgs<Contract['calls']['hasPendingHqConfigChange']>) =>
      singleQuery(publicClient!, call.hasPendingHqConfigChange(...args), {}, addressResolver) as Promise<
        CallReturn<'hasPendingHqConfigChange'>
      >,
    isValidHqConfig: (...args: ExtractArgs<Contract['calls']['isValidHqConfig']>) =>
      singleQuery(publicClient!, call.isValidHqConfig(...args), {}, addressResolver) as Promise<
        CallReturn<'isValidHqConfig'>
      >,
    canMintUndy: (...args: ExtractArgs<Contract['calls']['canMintUndy']>) =>
      singleQuery(publicClient!, call.canMintUndy(...args), {}, addressResolver) as Promise<CallReturn<'canMintUndy'>>,
    canSetTokenBlacklist: (...args: ExtractArgs<Contract['calls']['canSetTokenBlacklist']>) =>
      singleQuery(publicClient!, call.canSetTokenBlacklist(...args), {}, addressResolver) as Promise<
        CallReturn<'canSetTokenBlacklist'>
      >,
    undyToken: (...args: ExtractArgs<Contract['calls']['undyToken']>) =>
      singleQuery(publicClient!, call.undyToken(...args), {}, addressResolver) as Promise<CallReturn<'undyToken'>>,
    mintEnabled: (...args: ExtractArgs<Contract['calls']['mintEnabled']>) =>
      singleQuery(publicClient!, call.mintEnabled(...args), {}, addressResolver) as Promise<CallReturn<'mintEnabled'>>,
    hqConfig: (...args: ExtractArgs<Contract['calls']['hqConfig']>) =>
      singleQuery(publicClient!, call.hqConfig(...args), {}, addressResolver) as Promise<CallReturn<'hqConfig'>>,
    pendingHqConfig: (...args: ExtractArgs<Contract['calls']['pendingHqConfig']>) =>
      singleQuery(publicClient!, call.pendingHqConfig(...args), {}, addressResolver) as Promise<
        CallReturn<'pendingHqConfig'>
      >,

    // Mutations
    startGovernanceChange: (...args: ExtractArgs<Contract['mutations']['startGovernanceChange']>) =>
      mutate(walletClient!, mutation.startGovernanceChange, { addressResolver })(...args),
    confirmGovernanceChange: (...args: ExtractArgs<Contract['mutations']['confirmGovernanceChange']>) =>
      mutate(walletClient!, mutation.confirmGovernanceChange, { addressResolver })(...args),
    cancelGovernanceChange: (...args: ExtractArgs<Contract['mutations']['cancelGovernanceChange']>) =>
      mutate(walletClient!, mutation.cancelGovernanceChange, { addressResolver })(...args),
    relinquishGov: (...args: ExtractArgs<Contract['mutations']['relinquishGov']>) =>
      mutate(walletClient!, mutation.relinquishGov, { addressResolver })(...args),
    setGovTimeLock: (...args: ExtractArgs<Contract['mutations']['setGovTimeLock']>) =>
      mutate(walletClient!, mutation.setGovTimeLock, { addressResolver })(...args),
    finishUndyHqSetup: (...args: ExtractArgs<Contract['mutations']['finishUndyHqSetup']>) =>
      mutate(walletClient!, mutation.finishUndyHqSetup, { addressResolver })(...args),
    setRegistryTimeLock: (...args: ExtractArgs<Contract['mutations']['setRegistryTimeLock']>) =>
      mutate(walletClient!, mutation.setRegistryTimeLock, { addressResolver })(...args),
    setRegistryTimeLockAfterSetup: (...args: ExtractArgs<Contract['mutations']['setRegistryTimeLockAfterSetup']>) =>
      mutate(walletClient!, mutation.setRegistryTimeLockAfterSetup, { addressResolver })(...args),
    startAddNewAddressToRegistry: (...args: ExtractArgs<Contract['mutations']['startAddNewAddressToRegistry']>) =>
      mutate(walletClient!, mutation.startAddNewAddressToRegistry, { addressResolver })(...args),
    confirmNewAddressToRegistry: (...args: ExtractArgs<Contract['mutations']['confirmNewAddressToRegistry']>) =>
      mutate(walletClient!, mutation.confirmNewAddressToRegistry, { addressResolver })(...args),
    cancelNewAddressToRegistry: (...args: ExtractArgs<Contract['mutations']['cancelNewAddressToRegistry']>) =>
      mutate(walletClient!, mutation.cancelNewAddressToRegistry, { addressResolver })(...args),
    startAddressUpdateToRegistry: (...args: ExtractArgs<Contract['mutations']['startAddressUpdateToRegistry']>) =>
      mutate(walletClient!, mutation.startAddressUpdateToRegistry, { addressResolver })(...args),
    confirmAddressUpdateToRegistry: (...args: ExtractArgs<Contract['mutations']['confirmAddressUpdateToRegistry']>) =>
      mutate(walletClient!, mutation.confirmAddressUpdateToRegistry, { addressResolver })(...args),
    cancelAddressUpdateToRegistry: (...args: ExtractArgs<Contract['mutations']['cancelAddressUpdateToRegistry']>) =>
      mutate(walletClient!, mutation.cancelAddressUpdateToRegistry, { addressResolver })(...args),
    startAddressDisableInRegistry: (...args: ExtractArgs<Contract['mutations']['startAddressDisableInRegistry']>) =>
      mutate(walletClient!, mutation.startAddressDisableInRegistry, { addressResolver })(...args),
    confirmAddressDisableInRegistry: (...args: ExtractArgs<Contract['mutations']['confirmAddressDisableInRegistry']>) =>
      mutate(walletClient!, mutation.confirmAddressDisableInRegistry, { addressResolver })(...args),
    cancelAddressDisableInRegistry: (...args: ExtractArgs<Contract['mutations']['cancelAddressDisableInRegistry']>) =>
      mutate(walletClient!, mutation.cancelAddressDisableInRegistry, { addressResolver })(...args),
    initiateHqConfigChange: (...args: ExtractArgs<Contract['mutations']['initiateHqConfigChange']>) =>
      mutate(walletClient!, mutation.initiateHqConfigChange, { addressResolver })(...args),
    confirmHqConfigChange: (...args: ExtractArgs<Contract['mutations']['confirmHqConfigChange']>) =>
      mutate(walletClient!, mutation.confirmHqConfigChange, { addressResolver })(...args),
    cancelHqConfigChange: (...args: ExtractArgs<Contract['mutations']['cancelHqConfigChange']>) =>
      mutate(walletClient!, mutation.cancelHqConfigChange, { addressResolver })(...args),
    setUndyToken: (...args: ExtractArgs<Contract['mutations']['setUndyToken']>) =>
      mutate(walletClient!, mutation.setUndyToken, { addressResolver })(...args),
    setMintingEnabled: (...args: ExtractArgs<Contract['mutations']['setMintingEnabled']>) =>
      mutate(walletClient!, mutation.setMintingEnabled, { addressResolver })(...args),
    recoverFunds: (...args: ExtractArgs<Contract['mutations']['recoverFunds']>) =>
      mutate(walletClient!, mutation.recoverFunds, { addressResolver })(...args),
    recoverFundsMany: (...args: ExtractArgs<Contract['mutations']['recoverFundsMany']>) =>
      mutate(walletClient!, mutation.recoverFundsMany, { addressResolver })(...args),
  }
}
